version: "3.7"
services:
  relaychain-alice:
    ports:
      - 9944:9944
      - 9933:9933
      - 30333:30333
    volumes:
      - relaychain-alice:/data
    build:
      context: .
      dockerfile: relaychain.Dockerfile
    command:
      - --base-path=/data
      - --chain=/app/rococo-local.json
      - --validator
      - --ws-external
      - --rpc-external
      - --rpc-cors=all
      - --name=alice
      - --alice
      - --rpc-methods=unsafe
      - --no-beefy
      - --force-authoring
    environment: {}
    ulimits:
      &a1
      nofile:
        soft: 65536
        hard: 65536
  relaychain-bob:
    ports:
      - 9945:9944
      - 9934:9933
      - 30334:30333
    volumes:
      - relaychain-bob:/data
    build:
      context: .
      dockerfile: relaychain.Dockerfile
    command:
      - --base-path=/data
      - --chain=/app/rococo-local.json
      - --validator
      - --ws-external
      - --rpc-external
      - --rpc-cors=all
      - --name=bob
      - --bob
      - --rpc-methods=unsafe
      - --no-beefy
    environment: {}
    ulimits: *a1
  relaychain-charlie:
    ports:
      - 9946:9944
      - 9935:9933
      - 30335:30333
    volumes:
      - relaychain-charlie:/data
    build:
      context: .
      dockerfile: relaychain.Dockerfile
    command:
      - --base-path=/data
      - --chain=/app/rococo-local.json
      - --validator
      - --ws-external
      - --rpc-external
      - --rpc-cors=all
      - --name=charlie
      - --charlie
      - --rpc-methods=unsafe
      - --no-beefy
    environment: {}
    ulimits: *a1
  parachain-2022-0:
    ports:
      - 9954:9944
      - 9936:9933
      - 40333:30333
    volumes:
      - parachain-2022-0:/data
    build:
      context: .
      dockerfile: parachain-2022.Dockerfile
    command:
      - --base-path=/data
      - --chain=/app/staging-2022.json
      - --ws-external
      - --rpc-external
      - --rpc-cors=all
      - --name=parachain-2022-0
      - --collator
      - --parachain-id=2022
      - --execution=wasm
      - --node-key=d6cc47382dba173a61e79221ccc67edbde14dd5a79d244f53d3e8aa4ef20145a
      - --listen-addr=/ip4/0.0.0.0/tcp/30333
      - --
      - --chain=/app/rococo-local.json
      - --execution=wasm
      - --name=relaychain-alice
    environment: {}
    ulimits: *a1
  parachain-2022-1:
    ports:
      - 9955:9944
      - 9937:9933
      - 40334:30333
    volumes:
      - parachain-2022-1:/data
    build:
      context: .
      dockerfile: parachain-2022.Dockerfile
    command:
      - --base-path=/data
      - --chain=/app/staging-2022.json
      - --ws-external
      - --rpc-external
      - --rpc-cors=all
      - --name=parachain-2022-1
      - --collator
      - --parachain-id=2022
      - --execution=wasm
      - --bootnodes=/dns/parachain-2022-0/tcp/30333/p2p/12D3KooWH5AaxRC7Jz62qvzjjAo4TbTQWLtLVXq8N8CC6WSZY1ov
      - --listen-addr=/ip4/0.0.0.0/tcp/30333
      - --
      - --chain=/app/rococo-local.json
      - --execution=wasm
      - --name=relaychain-alice
    environment: {}
    ulimits: *a1
volumes:
  ? relaychain-alice
  ? relaychain-bob
  ? relaychain-charlie
  ? parachain-2022-0
  ? parachain-2022-1
