[package]
name = "ita-sgx-runtime"
version = "0.9.0"
authors = ['Trust Computing GmbH <info@litentry.com>', 'Integritee AG <hello@integritee.network>']
edition = "2021"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive"] }
scale-info = { workspace = true }

# local dependencies
itp-sgx-runtime-primitives = { workspace = true }

# Substrate dependencies
frame-executive = { workspace = true }
frame-support = { workspace = true }
frame-system = { workspace = true }
pallet-balances = { workspace = true }
pallet-sudo = { workspace = true }
pallet-timestamp = { workspace = true }
pallet-transaction-payment = { workspace = true }
sp-api = { workspace = true }
sp-core = { workspace = true }
sp-runtime = { workspace = true }
sp-std = { workspace = true }
sp-version = { workspace = true }

# Integritee dependencies
pallet-evm = { workspace = true, optional = true }

# Litentry
pallet-imt = { package = "pallet-identity-management-tee", path = "../../litentry/pallets/identity-management", default-features = false }
pallet-parentchain = { workspace = true }

[features]
default = ["std"]
# Compile the sgx-runtime with evm-pallet support in `no_std`.
evm = ["pallet-evm"]
# Compile the sgx-runtime with evm-pallet support in `std`.
evm_std = [
    "evm",            # Activate the `feature = evm` for the compiler flags.
    "std",
    "pallet-evm/std",
]
runtime-benchmarks = [
    "frame-support/runtime-benchmarks",
    "frame-system/runtime-benchmarks",
    "pallet-balances/runtime-benchmarks",
    "pallet-timestamp/runtime-benchmarks",
    "sp-runtime/runtime-benchmarks",
]
std = [
    "codec/std",
    "scale-info/std",
    "itp-sgx-runtime-primitives/std",
    "frame-executive/std",
    "frame-support/std",
    "frame-system/std",
    "pallet-balances/std",
    "pallet-sudo/std",
    "pallet-timestamp/std",
    "pallet-transaction-payment/std",
    "pallet-parentchain/std",
    "sp-api/std",
    "sp-core/std",
    "sp-runtime/std",
    "sp-std/std",
    "sp-version/std",
    # litentry
    "pallet-imt/std",
]
