[package]
name = "itc-parentchain-block-import-dispatcher"
version = "0.9.0"
authors = ['Trust Computing GmbH <info@litentry.com>', 'Integritee AG <hello@integritee.network>']
edition = "2021"

[dependencies]
# sgx dependencies
sgx_tstd = { workspace = true, optional = true }
sgx_types = { workspace = true }

# local dependencies
itc-parentchain-block-importer = { workspace = true }
itp-import-queue = { workspace = true }

# sgx enabled external libraries
thiserror_sgx = { workspace = true, optional = true }

# crates.io std-only compatible libraries (make sure these versions match with the sgx-enabled ones above)
thiserror = { workspace = true, optional = true }

# crates.io no-std compatible libraries
log = { workspace = true }

[dev-dependencies]
itc-parentchain-block-importer = { workspace = true, features = ["mocks"] }

[features]
default = ["std"]
std = [
    # local
    "itc-parentchain-block-importer/std",
    "itp-import-queue/std",
    # no-std compatible libraries
    "log/std",
    # std-only compatible libraries
    "thiserror",
]
sgx = [
    # sgx
    "sgx_tstd",
    # local
    "itc-parentchain-block-importer/sgx",
    "itp-import-queue/sgx",
    # sgx enabled external libraries
    "thiserror_sgx",
]

# feature to export mock implementations, only to be used for dev-dependencies!
mocks = []
