[package]
name = "itp-sgx-crypto"
version = "0.9.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aes = { workspace = true }
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive"] }
derive_more = { workspace = true }
log = { workspace = true }
ofb = { workspace = true }
serde_json = { workspace = true, features = ["alloc"], optional = true }

# sgx deps
serde_json_sgx = { workspace = true, optional = true }
sgx-crypto-helper = { workspace = true }
sgx_rand = { workspace = true, optional = true }
sgx_tstd = { workspace = true, optional = true }
sgx_types = { workspace = true }

# substrate 
sp-core = { workspace = true }

# local deps
itp-sgx-io = { workspace = true }

# test sgx deps
itp-sgx-temp-dir = { workspace = true, optional = true }

[features]
default = ["std"]
std = [
    "codec/std",
    "log/std",
    "itp-sgx-io/std",
    "sp-core/std",
    "serde_json/std",
    "sgx-crypto-helper/default",
]
sgx = [
    "sgx-crypto-helper/mesalock_sgx",
    "sgx_tstd",
    "sgx_rand",
    "itp-sgx-io/sgx",
    "serde_json_sgx",
]
mocks = []
test = [
    # features
    "mocks",
    "sgx",
    # deps
    "itp-sgx-temp-dir",
]
