[package]
name = "itp-storage"
version = "0.9.0"
authors = ['Trust Computing GmbH <info@litentry.com>', 'Integritee AG <hello@integritee.network>']
edition = "2021"

[dependencies]
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["chain-error"] }
derive_more = { workspace = true }
frame-metadata = { version = "15.1.0", features = ["v14"], default-features = false }
hash-db = { version = "0.15.2", default-features = false }
thiserror = { workspace = true, optional = true }

# sgx deps
sgx_tstd = { workspace = true, optional = true }
thiserror_sgx = { workspace = true, optional = true }

# substrate deps
frame-support = { workspace = true }
sp-core = { workspace = true }
sp-runtime = { workspace = true }
sp-std = { workspace = true }
sp-trie = { workspace = true }

# integritee
itp-types = { workspace = true }

[dev-dependencies]
sp-state-machine = { workspace = true }

[features]
default = ["std"]
std = [
    "codec/std",
    "frame-metadata/std",
    "frame-support/std",
    "hash-db/std",
    "itp-types/std",
    "sp-core/std",
    "sp-runtime/std",
    "sp-std/std",
    "sp-trie/std",
    "thiserror",
]
sgx = [
    "sgx_tstd",
    "thiserror_sgx",
]
test = []
