version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    labels: ["I1-low", "F7-devop"]
    # Handle updates for crates from github.com/paritytech/substrate manually.
    ignore:
      - dependency-name: "substrate-*"
      - dependency-name: "polkadot-*"
      - dependency-name: "sc-*"
      - dependency-name: "sp-*"
      - dependency-name: "frame-*"
      - dependency-name: "cumulus-*"
      - dependency-name: "pallet-*"
      - dependency-name: "xcm*"
      - dependency-name: "parachain-runtime"
      - dependency-name: "litentry-*"
      - dependency-name: "fork-tree"
      - dependency-name: "remote-externalities"
      - dependency-name: "beefy-*"
      - dependency-name: "try-runtime-*"
      - dependency-name: "test-runner"
      - dependency-name: "generate-bags"
    schedule:
      interval: "weekly"
