# This is used by the action https://github.com/dorny/paths-filter to run jobs conditionally
# Put all defined set of files here, similar to https://github.com/getsentry/sentry/blob/master/.github/workflows/getsentry-dispatch.yml

parachain_src: &parachain_src
  - 'node/**'
  - 'pallets/**'
  - 'primitives/**'
  - 'runtime/**'
  - 'mock-tee-primitives/**'
  - 'docker/Dockerfile'
  - 'docker/bridge.Dockerfile'
  - 'Cargo.lock'
  - 'Cargo.toml'
  - 'rust-toolchain.toml'

parachain_ts_tests: &parachain_ts_tests
  - 'ts-tests/**'

tee_src: &tee_src
  - '!(tee-worker)/ts-tests/**'
  - 'tee-worker/**'

tee_ts_tests: &tee_ts_tests
  - 'tee-worker/ts-tests/**'
