[package]
edition = "2021"
name = "lc-mock-server"
version = "0.1.0"

[dependencies]
hex = { workspace = true }
log = { workspace = true }
serde_json = { workspace = true, features = ["alloc"] }
tokio = { workspace = true, features = ["full"] }
warp = { workspace = true }

# Substrate
sp-core = { workspace = true }

# Internal dependencies
ita-stf = { workspace = true }
itp-rpc = { workspace = true }
lc-data-providers = { workspace = true }
litentry-primitives = { workspace = true }
