include = ["**/Cargo.toml"]

[formatting]
align_entries = false
align_comments = false
array_trailing_comma = true
array_auto_expand = true
array_auto_collapse = true
compact_arrays = true
compact_inline_tables = false
compact_entries = false
column_width = 80
indent_tables = false
indent_entries = false
indent_string =  "	"
trailing_newline = true
reorder_keys = true
allowed_blank_lines = 2
crlf = false


# Default values
# [formatting]
# align_entries = false
# align_comments = true
# array_trailing_comma = true
# array_auto_expand = true
# array_auto_collapse = true
# compact_arrays = true
# compact_inline_tables = false
# compact_entries = false
# column_width = 80
# indent_tables = false
# indent_entries = false
# indent_string =  "  "
# trailing_newline = true
# reorder_keys = false
# allowed_blank_lines = 2
# crlf = false
