[workspace]
members = [
  'node',
  'pallets/bridge',
  'pallets/bridge-transfer',
  'pallets/drop3',
  'pallets/extrinsic-filter',
  'pallets/identity-management',
  'pallets/identity-management-mock',
  'pallets/vc-management',
  'pallets/sidechain',
  'pallets/teeracle',
  'pallets/teerex',
  'pallets/parentchain',
  'pallets/test-utils',
  'pallets/whitelist',
  'primitives/common',
  'primitives/core',
  'primitives/sidechain',
  'primitives/teeracle',
  'primitives/teerex',
  'runtime/litentry',
  'runtime/litmus',
  'runtime/rococo',
  'runtime/common',
]

[profile.release]
opt-level = 3
panic = "unwind"

[profile.dev]
# https://internals.rust-lang.org/t/help-test-faster-incremental-debug-macos-builds-on-nightly/14016
split-debuginfo = 'unpacked'

[profile.dev.package.backtrace]
inherits = "release"

[profile.production]
codegen-units = 1
inherits = "release"
lto = true
strip = "symbols"
