[workspace]
members = [
    'node',
    'pallets/bridge',
    'pallets/bridge-transfer',
    'pallets/drop3',
    'pallets/extrinsic-filter',
    'pallets/identity-management',
    'primitives',
    'runtime/litentry',
    'runtime/litmus',
    'runtime/rococo',
    'runtime/moonbase',
    'runtime/common',
]

[profile.release]
panic = "unwind"
opt-level = 3

[profile.dev]
# https://internals.rust-lang.org/t/help-test-faster-incremental-debug-macos-builds-on-nightly/14016
split-debuginfo = 'unpacked'

[profile.dev.package.backtrace]
inherits = "release"

[profile.production]
inherits = "release"
lto = true
codegen-units = 1
strip = "symbols"