[package]
name = "lc-scheduled-enclave"
version = "0.8.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
codec = { version = "3.0.0", default-features = false, features = ["derive"], package = "parity-scale-codec" }
lazy_static = { version = "1.1.0", features = ["spin_no_std"] }
log = { version = "0.4", default-features = false }
sp-std = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.37" }
thiserror = { version = "1.0.26", optional = true }

# sgx-deps
sgx_tstd = { branch = "master", git = "https://github.com/apache/teaclave-sgx-sdk.git", features = ["untrusted_fs"], optional = true }
sgx_types = { branch = "master", git = "https://github.com/apache/teaclave-sgx-sdk.git" }
thiserror-sgx = { package = "thiserror", git = "https://github.com/mesalock-linux/thiserror-sgx", tag = "sgx_1.1.3", optional = true }

# local dependencies
itp-component-container = { path = "../../../core-primitives/component-container", default-features = false }
itp-settings = { path = "../../../core-primitives/settings" }
itp-sgx-io = { path = "../../../core-primitives/sgx/io", default-features = false }
itp-types = { path = "../../../core-primitives/types", default-features = false }
litentry-primitives = { path = "../../primitives", default-features = false }

[features]
default = ["std"]
sgx = [
    "sgx_tstd",
    "thiserror-sgx",
    "itp-sgx-io/sgx",
    "itp-component-container/sgx",
    "litentry-primitives/sgx",
]
std = [
    "thiserror",
    "itp-sgx-io/std",
    "itp-types/std",
    "itp-component-container/std",
    "litentry-primitives/std",
    "sp-std/std",
    "codec/std",
]
