[package]
name = "lc-scheduled-enclave"
version = "0.8.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
codec = { version = "3.0.0", default-features = false, features = ["derive"], package = "parity-scale-codec" }
lazy_static = { workspace = true, features = ["spin_no_std"] }
log = { workspace = true }
sp-std = { workspace = true }
thiserror = { workspace = true, optional = true }

# sgx-deps
sgx_tstd = { workspace = true, features = ["untrusted_fs"], optional = true }
thiserror_sgx = { workspace = true, optional = true }

# local dependencies
itp-settings = { workspace = true }
itp-sgx-io = { workspace = true }
itp-types = { workspace = true }

[features]
default = ["std"]
sgx = [
    "sgx_tstd",
    "thiserror_sgx",
    "itp-sgx-io/sgx",
]
std = [
    "thiserror",
    "itp-sgx-io/std",
    "itp-types/std",
    "sp-std/std",
    "codec/std",
]
