[package]
name = "test-utils"
description = "A crate for common utilities for tests"
version = "0.1.0"
authors = ['Litentry Technologies GmbH <info@litentry.com>']
homepage = 'https://litentry.com/'
repository = 'https://github.com/litentry/litentry-parachain'
license = "Apache-2.0"
edition = "2021"

[dependencies]
hex-literal = { version = "0.4.1" }
log = { version = "0.4", default-features = false }

[dependencies.teerex-primitives]
default-features = false
package = "teerex-primitives"
path = "../../primitives/teerex"


[features]
default = ['std']
std = [
    "log/std",
    "teerex-primitives/std",
]
