[package]
name = "itp-stf-primitives"
version = "0.9.0"
authors = ['Trust Computing GmbH <info@litentry.com>', 'Integritee AG <hello@integritee.network>']
edition = "2021"

[dependencies]
# crates.io
codec = { version = "3.0.0", default-features = false, features = ["derive"], package = "parity-scale-codec" }
derive_more = { workspace = true }
itp-sgx-runtime-primitives = { workspace = true }
sp-core = { workspace = true }
sp-runtime = { workspace = true }
sp-std = { workspace = true }

# litentry
litentry-primitives = { path = "../../litentry/primitives", default-features = false }

[features]
default = ["std"]
std = [
    # crates.io
    "codec/std",
    # substrate
    "sp-core/std",
    "sp-std/std",
    "sp-runtime/std",
    "itp-sgx-runtime-primitives/std",
    # litentry
    "litentry-primitives/std",
]
