[package]
name = "itp-types"
version = "0.9.0"
authors = ['Trust Computing GmbH <info@litentry.com>', 'Integritee AG <hello@integritee.network>']
homepage = 'https://litentry.com/'
repository = 'https://github.com/litentry/litentry-parachain'
license = "Apache-2.0"
edition = "2021"

[dependencies]
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive"] }

# local dependencies
itp-sgx-crypto = { workspace = true }
itp-sgx-runtime-primitives = { workspace = true }
itp-stf-primitives = { workspace = true }
itp-utils = { workspace = true }

# scs
substrate-api-client = { workspace = true, features = ["sync-api"] }

# substrate-deps
frame-system = { workspace = true }
pallet-balances = { workspace = true }
sp-core = { workspace = true }
sp-runtime = { workspace = true }
sp-std = { workspace = true }

# litentry
litentry-primitives = { workspace = true }

[features]
default = ["std"]
std = [
    "codec/std",
    "itp-sgx-crypto/std",
    "itp-sgx-runtime-primitives/std",
    "itp-stf-primitives/std",
    "itp-utils/std",
    "substrate-api-client/std",
    # substrate
    "frame-system/std",
    "pallet-balances/std",
    "sp-std/std",
    "sp-core/std",
    "sp-runtime/std",
    # litentry
    "litentry-primitives/std",
]
test = []
