[package]
name = "itc-rpc-client"
version = "0.9.0"
authors = ['Trust Computing GmbH <info@litentry.com>', 'Integritee AG <hello@integritee.network>']
edition = "2021"

[dependencies]
# crates.io
base58 = { workspace = true }
codec = { package = "parity-scale-codec", version = "3.0.0", features = ["derive"] }
log = { workspace = true }
openssl = { workspace = true }
parking_lot = { workspace = true }
serde_json = { workspace = true }
sgx_crypto_helper = { workspace = true }
thiserror = { workspace = true }
url = { workspace = true }
ws = { workspace = true }

# parity
frame-metadata = { workspace = true }
sp-core = { workspace = true }

# local
itp-api-client-types = { workspace = true }
itp-rpc = { workspace = true }
itp-types = { workspace = true }
itp-utils = { workspace = true }

# litentry
ita-stf = { workspace = true, features = ["std"] }
itp-stf-primitives = { workspace = true }
litentry-primitives = { workspace = true }

[dev-dependencies]
env_logger = { workspace = true }
itc-tls-websocket-server = { workspace = true, features = ["mocks"] }
itp-networking-utils = { workspace = true }
rustls = { workspace = true }
