[package]
authors = ["Trust Computing GmbH <info@litentry.com>"]
edition = '2021'
name = 'pallet-evm-precompile-parachain-staking'
version = '0.9.17'

[dependencies]
log = { version = "0.4", default-features = false }
num_enum = { version = "0.6.1", default-features = false }
parity-scale-codec = { version = "3.0.0", default-features = false, features = ["derive", "max-encoded-len"] }
rustc-hex = { version = "2.0.1", default-features = false }

# Local
pallet-parachain-staking = { path = "../../pallets/parachain-staking", default-features = false }
precompile-utils = { path = "../../precompiles/utils", default-features = false }

# Substrate
frame-support = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.42", default-features = false }
frame-system = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.42", default-features = false }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.42", default-features = false }
sp-io = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.42", default-features = false }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.42", default-features = false }
sp-std = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.42", default-features = false }

# Frontier
fp-evm = { git = "https://github.com/paritytech/frontier", branch = "polkadot-v0.9.42", default-features = false }
pallet-evm = { git = "https://github.com/paritytech/frontier", branch = "polkadot-v0.9.42", default-features = false, features = ["forbid-evm-reentrancy"] }

[dev-dependencies]
derive_more = { version = "0.99.5", default-features = false }
scale-info = { version = "2.10.0", default-features = false, features = ["derive"] }
serde = { version = "1.0", default-features = false }
sha3 = { version = "0.10", default-features = false }

# Local
precompile-utils = { path = "../../precompiles/utils", default-features = false, features = ["testing"] }

# Substrate
pallet-balances = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.42", features = ["insecure_zero_ed"] }
pallet-timestamp = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.42", default-features = false }

[features]
default = ["std"]
std = [
    "fp-evm/std",
    "frame-support/std",
    "frame-system/std",
    "pallet-parachain-staking/std",
    "parity-scale-codec/std",
    "precompile-utils/std",
    "sp-core/std",
    "sp-runtime/std",
    "sp-std/std",
]
