[package]
authors = ["Trust Computing GmbH <info@litentry.com>"]
edition = '2021'
name = 'staking-primitives'
version = '0.9.12'

[dependencies]
pallet-parachain-staking = { path = "../../pallets/parachain-staking", default-features = false }

[features]
default = ["std"]
std = [
    "pallet-parachain-staking/std",
]
