[package]
name = "itc-peer-top-broadcaster"
version = "0.1.0"
authors = ['Trust Computing GmbH <info@litentry.com>']
edition = "2021"

[dependencies]
# sgx dependencies
sgx_tstd = { workspace = true, optional = true }

# no-std dependencies
log = { workspace = true }

# local dependencies
itc-direct-rpc-client = { workspace = true }
itc-direct-rpc-server = { workspace = true }
itp-rpc = { workspace = true }
itp-stf-primitives = { workspace = true }
itp-types = { workspace = true }
itp-utils = { workspace = true }

# litentry
litentry-primitives = { workspace = true }

[dev-dependencies]
itc-direct-rpc-server = { workspace = true, features = ["mocks"] }


[features]
default = ["std"]
sgx = [
    "sgx_tstd",
    "itc-direct-rpc-server/sgx",
    "itc-direct-rpc-client/sgx",
    "itp-rpc/sgx",
    "litentry-primitives/sgx",
]
std = [
    "itp-stf-primitives/std",
    "itp-types/std",
    "itp-utils/std",
    "log/std",
    "itc-direct-rpc-server/std",
    "itc-direct-rpc-client/std",
    "itp-rpc/std",
    "litentry-primitives/std",
]
