[package]
name = "itp-stf-executor"
version = "0.9.0"
authors = ['Trust Computing GmbH <info@litentry.com>', 'Integritee AG <hello@integritee.network>']
edition = "2021"

[dependencies]
hex = { workspace = true, features = ["alloc"] }

# sgx dependencies
sgx_tstd = { workspace = true, optional = true, features = ["untrusted_time"] }
sgx_types = { workspace = true }

# local dependencies
itp-enclave-metrics = { workspace = true }
itp-node-api = { workspace = true }
itp-ocall-api = { workspace = true }
itp-sgx-crypto = { workspace = true }
itp-sgx-externalities = { workspace = true }
itp-stf-interface = { workspace = true }
itp-stf-primitives = { workspace = true }
itp-stf-state-handler = { workspace = true }
itp-stf-state-observer = { workspace = true }
itp-time-utils = { workspace = true }
itp-top-pool-author = { workspace = true }
itp-types = { workspace = true }

# sgx enabled external libraries
thiserror_sgx = { optional = true, workspace = true }

# std compatible external libraries (make sure these versions match with the sgx-enabled ones above)
thiserror = { workspace = true, optional = true }

# no-std dependencies
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive"] }
log = { workspace = true }

# substrate dependencies
sp-core = { workspace = true }
sp-runtime = { workspace = true }

# dev dependencies
itc-parentchain-test = { workspace = true, optional = true }
itp-test = { workspace = true, optional = true }

# litentry
litentry-primitives = { workspace = true }

[dev-dependencies]
itp-stf-state-observer = { workspace = true, features = ["mocks"] }
itp-stf-interface = { workspace = true, features = ["mocks"] }
itp-top-pool = { workspace = true, features = ["mocks"] }
itp-test = { workspace = true }

[features]
default = ["std"]
std = [
    # local
    "itp-node-api/std",
    "itp-ocall-api/std",
    "itp-sgx-crypto/std",
    "itp-sgx-externalities/std",
    "itp-stf-interface/std",
    "itp-stf-state-handler/std",
    "itp-stf-state-observer/std",
    "itp-top-pool-author/std",
    "itp-types/std",
    "itp-time-utils/std",
    # crates.io
    "log/std",
    "codec/std",
    # substrate
    "sp-core/std",
    "sp-runtime/std",
    "thiserror",
    # litentry
    "litentry-primitives/std",
]
sgx = [
    "sgx_tstd",
    "itp-node-api/sgx",
    "itp-sgx-crypto/sgx",
    "itp-sgx-externalities/sgx",
    "itp-stf-state-handler/sgx",
    "itp-stf-state-observer/sgx",
    "itp-top-pool-author/sgx",
    "itp-time-utils/sgx",
    "thiserror_sgx",
    # litentry
    "litentry-primitives/sgx",
]
test = [
    "itc-parentchain-test",
    "itp-node-api/mocks",
    "itp-test",
]
mocks = []
