[package]
name = "ita-parentchain-interface"
version = "0.9.0"
authors = ["Integritee AG <hello@integritee.network>"]
edition = "2021"

[dependencies]
# sgx dependencies
sgx_tstd = { workspace = true, optional = true }

# local dependencies
ita-sgx-runtime = { workspace = true }
ita-stf = { workspace = true }
itc-parentchain-indirect-calls-executor = { workspace = true }
itp-api-client-types = { workspace = true }
itp-node-api = { workspace = true }
itp-stf-primitives = { workspace = true }
itp-types = { workspace = true }
itp-utils = { workspace = true }

# no-std compatible libraries
bs58 = { workspace = true }
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive"] }
log = { workspace = true }

# substrate dep
sp-core = { workspace = true }
sp-runtime = { workspace = true }

# litentry
lc-scheduled-enclave = { workspace = true, optional = true }
litentry-hex-utils = { workspace = true }
litentry-primitives = { workspace = true }
sp-std = { workspace = true }

[dev-dependencies]
env_logger = "0.9.0"
itp-node-api = { workspace = true, features = ["mocks"] }
itp-sgx-crypto = { workspace = true, features = ["mocks"] }
itp-stf-executor = { workspace = true, features = ["mocks"] }
itp-test = { workspace = true }
itp-top-pool-author = { workspace = true, features = ["mocks"] }
itc-parentchain-test = { workspace = true }


[features]
default = ["std"]
std = [
    "bs58/std",
    "codec/std",
    "ita-sgx-runtime/std",
    "ita-stf/std",
    "itc-parentchain-indirect-calls-executor/std",
    "itp-api-client-types/std",
    "itp-node-api/std",
    "itp-sgx-crypto/std",
    "itp-stf-executor/std",
    "itp-stf-primitives/std",
    "itp-top-pool-author/std",
    "itp-types/std",
    "itp-utils/std",
    "log/std",
    #substrate
    "sp-core/std",
    "sp-runtime/std",
    "litentry-primitives/std",
    "lc-scheduled-enclave/std",
    "sp-std/std",
]
sgx = [
    "sgx_tstd",
    "ita-stf/sgx",
    "itc-parentchain-indirect-calls-executor/sgx",
    "itp-node-api/sgx",
    "itp-sgx-crypto/sgx",
    "itp-stf-executor/sgx",
    "itp-top-pool-author/sgx",
    "litentry-primitives/sgx",
    "lc-scheduled-enclave/sgx",
]
