[package]
name = 'runtime-common'
version = '0.9.8'
authors = ["Litentry Dev"]
edition = '2021'

[dependencies]

# substrate
frame-support = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.24", default-features = false }
frame-system = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.24", default-features = false }
pallet-collective = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.24", default-features = false }
pallet-membership = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.24", default-features = false }

# local
primitives = { package = "primitives", path = "../../primitives", default-features = false }

[features]
default = ["std"]
std = [
	"frame-support/std",
	"frame-system/std",
	"pallet-collective/std",
	"pallet-membership/std",
	"primitives/std",
]
