[package]
authors = ["Trust Computing GmbH <info@litentry.com>"]
edition = "2021"
name = "lc-stf-task-receiver"
version = "0.1.0"

[dependencies]
# std dependencies
futures = { workspace = true, optional = true }
thiserror = { workspace = true, optional = true }
threadpool = { workspace = true, optional = true }

# sgx dependencies
futures_sgx = { workspace = true, optional = true }
hex-sgx = { workspace = true, optional = true }
sgx_tstd = { workspace = true, features = ["net", "thread"], optional = true }
thiserror_sgx = { workspace = true, optional = true }
threadpool_sgx = { workspace = true, optional = true }
url_sgx = { workspace = true, optional = true }

# no_std dependencies
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive"] }
log = { workspace = true }
sp-core = { workspace = true }

# internal dependencies
ita-stf = { workspace = true }
itc-peer-top-broadcaster = { workspace = true }
itp-types = { workspace = true }

itp-enclave-metrics = { workspace = true }
itp-ocall-api = { workspace = true }
itp-sgx-crypto = { workspace = true }
itp-sgx-externalities = { workspace = true }
itp-stf-executor = { workspace = true }
itp-stf-state-handler = { workspace = true }
itp-top-pool-author = { workspace = true }
itp-utils = { workspace = true }


# litentry
frame-support = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.42" }
ita-sgx-runtime = { path = "../../../../app-libs/sgx-runtime", default-features = false }
lc-assertion-build = { path = "../../assertion-build", default-features = false }
lc-assertion-build-v2 = { path = "../../assertion-build-v2", default-features = false }
lc-credentials = { path = "../../credentials", default-features = false }
lc-data-providers = { path = "../../data-providers", default-features = false }
lc-identity-verification = { path = "../../identity-verification", default-features = false }
lc-stf-task-sender = { path = "../sender", default-features = false }
litentry-primitives = { path = "../../../primitives", default-features = false }

[dev-dependencies]
sgx_crypto_helper = { version = "1.1.6", git = "https://github.com/apache/incubator-teaclave-sgx-sdk", branch = "master" }
itp-test = { path = "../../../../core-primitives/test" }
itp-top-pool-author = { path = "../../../../core-primitives/top-pool-author", features = ["mocks"] }
itp-top-pool = { path = "../../../../core-primitives/top-pool", features = ["mocks"] }
itp-stf-executor = { path = "../../../../core-primitives/stf-executor", features = ["mocks"] }
base58 = "0.2"
jsonrpc-core = { version = "18" }
lazy_static = { version = "1.1.0" }
hex = "0.4.2"

[features]
default = ["std"]
sgx = [
    "threadpool_sgx",
    "futures_sgx",
    "hex-sgx",
    "sgx_tstd",
    "thiserror_sgx",
    "url_sgx",
    "ita-stf/sgx",
    "itc-peer-top-broadcaster/sgx",
    "itp-sgx-externalities/sgx",
    "itp-stf-executor/sgx",
    "itp-stf-state-handler/sgx",
    "itp-top-pool-author/sgx",
    "sp-core/full_crypto",
    "litentry-primitives/sgx",
    "lc-stf-task-sender/sgx",
    "lc-identity-verification/sgx",
    "lc-assertion-build/sgx",
    "lc-assertion-build-v2/sgx",
    "lc-credentials/sgx",
    "lc-data-providers/sgx",
]
std = [
    "threadpool",
    "futures",
    "log/std",
    "thiserror",
    "itc-peer-top-broadcaster/std",
    "itp-types/std",
    "itp-top-pool-author/std",
    "itp-utils/std",
    "itp-stf-executor/std",
    "itp-stf-state-handler/std",
    "sp-core/std",
    "litentry-primitives/std",
    "lc-stf-task-sender/std",
    "lc-identity-verification/std",
    "lc-assertion-build/std",
    "lc-assertion-build-v2/std",
    "ita-sgx-runtime/std",
    "frame-support/std",
    "lc-credentials/std",
    "lc-data-providers/std",
]
