[package]
name = "itp-enclave-api"
version = "0.9.0"
authors = ['Trust Computing GmbH <info@litentry.com>', 'Integritee AG <hello@integritee.network>']
edition = "2021"

[dependencies]
codec = { package = "parity-scale-codec", version = "3.0.0", features = ["derive"] }
hex = { workspace = true }
log = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }

sgx_crypto_helper = { workspace = true }
sgx_types = { workspace = true }
sgx_urts = { optional = true, workspace = true }

frame-support = { workspace = true }
sp-core = { workspace = true }
sp-runtime = { workspace = true }

itc-parentchain = { workspace = true }
itp-enclave-api-ffi = { workspace = true }
itp-settings = { workspace = true }
itp-storage = { workspace = true }
itp-types = { workspace = true }

# litentry
pallet-teebag = { path = "../../../pallets/teebag", default-features = false }

[features]
default = []
implement-ffi = [
    "sgx_urts",
    "itp-enclave-api-ffi/link-sgx-libs",
]
