[package]
authors = ["Trust Computing GmbH <info@litentry.com>"]
edition = "2021"
name = "lc-direct-call"
version = "0.1.0"

[dependencies]
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive"] }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.42", default-features = false, features = ["full_crypto"] }
sp-io = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.42", default-features = false }

# internal dependencies
bc-relayer-registry = { path = "../../../bitacross/core/bc-relayer-registry", default-features = false }
itp-sgx-crypto = { path = "../../../core-primitives/sgx/crypto", default-features = false }
itp-stf-primitives = { path = "../../../core-primitives/stf-primitives", default-features = false }
litentry-primitives = { path = "../../primitives", default-features = false }
parentchain-primitives = { package = "core-primitives", path = "../../../../primitives/core", default-features = false }

# sgx dependencies
sgx_tstd = { git = "https://github.com/apache/teaclave-sgx-sdk.git", branch = "master", optional = true }

[dev-dependencies]
k256 = { version = "0.13.3", features = ["ecdsa-core", "schnorr"] }
rand = { version = "0.7" }
hex = { version = "0.4" }

[features]
default = ["std"]
production = [
    "parentchain-primitives/production",
]
sgx = [
    "sgx_tstd",
    "bc-relayer-registry/sgx",
    "litentry-primitives/sgx",
    "itp-sgx-crypto/sgx",
]
std = [
    "bc-relayer-registry/std",
    "itp-stf-primitives/std",
    "itp-sgx-crypto/std",
    "litentry-primitives/std",
    "sp-core/std",
    "sp-io/std",
    "parentchain-primitives/std",
]
test = [
    "itp-sgx-crypto/mocks",
]
