services:
  lit-set-heartbeat-timeout:
    image: litentry/bitacross-cli:latest
    container_name: litentry-set-heartbeat-timeout
    volumes:
      - ../cli:/usr/local/worker-cli
    build:
      context: ..
      dockerfile: build.Dockerfile
      target: deployed-client
    depends_on:
      litentry-node:
        condition: service_healthy
      bitacross-worker-1:
        condition: service_healthy
    networks:
      - litentry-test-network
    entrypoint:
      "/usr/local/worker-cli/lit_set_heartbeat_timeout.sh -p 9912 -u ws://litentry-node
      -V wss://bitacross-worker-1 -A 2011 -W wss://bitacross-worker-2 -B 2012 -C /usr/local/bin/bitacross-cli 2>&1"
    restart: "no"
networks:
  litentry-test-network:
    driver: bridge