services:
    lit-di-evm-identity-test:
        image: litentry/bitacross-cli:latest
        container_name: litentry-di-evm-identity-test
        volumes:
            - ../ts-tests:/ts-tests
            - ../client-api:/client-api
            - ../cli:/usr/local/worker-cli
        build:
            context: ..
            dockerfile: build.Dockerfile
            target: deployed-client
        depends_on:
            litentry-node:
                condition: service_healthy
            bitacross-worker-1:
                condition: service_healthy
        networks:
            - litentry-test-network
        entrypoint: "bash -c '/usr/local/worker-cli/lit_ts_integration_test.sh test-di-evm-identity 2>&1' "
        restart: "no"
networks:
    litentry-test-network:
        driver: bridge
