[package]
authors = ["Parity Technologies <admin@parity.io>"]
description = "Set scope-limited values can can be accessed statically"
edition = "2021"
license = "Apache-2.0"
name = "environmental"
version = "1.1.3"

[dependencies]
sgx_tstd = { branch = "master", git = "https://github.com/apache/teaclave-sgx-sdk.git", optional = true, features = ["thread"] }

[features]
default = ["std"]
sgx = ["sgx_tstd"]
std = []
