[package]
name = "itp-ocall-api"
version = "0.9.0"
authors = ['Trust Computing GmbH <info@litentry.com>', 'Integritee AG <hello@integritee.network>']
edition = "2021"

[dependencies]
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive"] }
derive_more = { workspace = true }

# sgx deps
sgx_types = { workspace = true }

# substrate deps
sp-core = { workspace = true }
sp-runtime = { workspace = true }
sp-std = { workspace = true }

# local deps
itp-storage = { workspace = true }
itp-types = { workspace = true }

[features]
default = ["std"]
std = [
    "codec/std",
    "sp-core/std",
    "sp-runtime/std",
    "sp-std/std",
    "itp-storage/std",
    "itp-types/std",
]
