[package]
authors = ["Integritee AG <hello@integritee.network>"]
edition = "2021"
name = "itp-settings"
version = "0.9.0"

[dependencies]


[features]
offchain-worker = []
production = []
sidechain = []
teeracle = []
