[package]
name = "itp-settings"
version = "0.9.0"
authors = ['Trust Computing GmbH <info@litentry.com>', 'Integritee AG <hello@integritee.network>']
edition = "2021"

[dependencies]
litentry-primitives = { path = "../../litentry/primitives", default-features = false }

[features]
production = [
    "litentry-primitives/production",
]
sidechain = []
offchain-worker = []
