# A parachain-launch (https://github.com/open-web3-stack/parachain-launch) config
# used in dev env
# contains 2 relaychain nodes + 1 parachain node
#
# Relaychain Configuration
relaychain:
  image: parity/polkadot:v0.9.42
  chain: rococo-local
  env:
    RUST_LOG: parachain::candidate-backing=trace,parachain::candidate-selection=trace,parachain::pvf=trace,parachain::collator-protocol=trace,parachain::provisioner=trace
  flags:
    - --rpc-methods=unsafe
    - --execution=wasm
  nodes:
    - name: alice
      wsPort: 9946
      rpcPort: 9936
      port: 30336
    - name: bob
      wsPort: 9947
      rpcPort: 9937
      port: 30337

# Parachain Configuration
parachains:
- image: litentry/litentry-parachain:latest
  chain:
    base: litentry-dev
  id: 2013
  parachain: true
  flags:
    - --rpc-methods=unsafe
    - --force-authoring
    - --execution=wasm
    - --state-pruning=archive
    - --blocks-pruning=archive
  relaychainFlags:
    - --execution=wasm
  env:
    RUST_LOG: sc_basic_authorship=trace,cumulus-consensus=trace,cumulus-collator=trace,collator_protocol=trace,collation_generation=trace,aura=debug
  volumePath: /data
  nodes:
  - flags:
    - --alice
    wsPort: 9944
    rpcPort: 9933
    port: 30333
