[package]
authors = ["Trust Computing GmbH <info@litentry.com>"]
edition = "2021"
name = "lc-credentials-v2"
version = "0.1.0"

[dependencies]
# std dependencies
thiserror = { version = "1.0.38", optional = true }

# sgx dependencies
sgx_tstd = { branch = "master", git = "https://github.com/apache/teaclave-sgx-sdk.git", optional = true, features = ["net", "thread"] }
thiserror_sgx = { package = "thiserror", git = "https://github.com/mesalock-linux/thiserror-sgx", tag = "sgx_1.1.3", optional = true }

# no_std dependencies
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive"] }
log = { version = "0.4", default-features = false }

# internal dependencies
itp-stf-primitives = { default-features = false, path = "../../../core-primitives/stf-primitives" }
itp-time-utils = { path = "../../../core-primitives/time-utils", default-features = false }
itp-types = { path = "../../../core-primitives/types", default-features = false }
itp-utils = { path = "../../../core-primitives/utils", default-features = false }

# litentry
lc-common = { path = "../common", default-features = false }
lc-credentials = { path = "../credentials", default-features = false }
litentry-primitives = { path = "../../primitives", default-features = false }

[features]
default = ["std"]
async = []
async_std = ["async", "std", "lc-credentials/async_std"]
async_sgx = ["async", "sgx", "lc-credentials/async_sgx"]
sgx = [
    "sgx_tstd",
    "thiserror_sgx",
    "litentry-primitives/sgx",
    "itp-time-utils/sgx",
    "lc-common/sgx",
    "lc-credentials/sgx",
]
std = [
    "log/std",
    "thiserror",
    "itp-types/std",
    "itp-utils/std",
    "litentry-primitives/std",
    "itp-time-utils/std",
    "lc-common/std",
    "lc-credentials/std",
]
