[package]
name = "itc-rpc-server"
version = "0.9.0"
authors = ['Trust Computing GmbH <info@litentry.com>', 'Integritee AG <hello@integritee.network>']
edition = "2021"

[dependencies]
anyhow = { workspace = true }
jsonrpsee = { workspace = true }
log = { workspace = true }
tokio = { workspace = true }

# local
itp-enclave-api = { workspace = true }
itp-rpc = { workspace = true }
itp-utils = { workspace = true }
its-peer-fetch = { workspace = true }
its-primitives = { workspace = true }
its-rpc-handler = { workspace = true }
its-storage = { workspace = true }

[features]
default = ["std"]
std = []

[dev-dependencies]
env_logger = { version = "*" }
sp-core = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.42" }
its-test = { path = "../../sidechain/test" }
parity-scale-codec = "3.0.0"
