[package]
authors = ['Trust Computing GmbH <info@litentry.com>', 'Integritee AG <hello@integritee.network>']
edition = '2021'
homepage = 'https://litentry.com'
name = 'pallet-teebag'
description = 'Pallet for tee-worker registration and management'
repository = 'https://github.com/litentry/litentry-parachain'
license = 'GPL-3.0'
version = '0.1.0'

[dependencies]
base64 = { version = "0.13", default-features = false, features = ["alloc"] }
chrono = { version = "0.4", default-features = false, features = ["serde"] }
codec = { version = "3.0.0", default-features = false, features = ["derive"], package = "parity-scale-codec" }
der = { default-features = false, version = "0.6.0" }
hex = { default-features = false, version = "0.4.3", features = ["alloc"] }
hex-literal = { version = "0.4", default-features = false }
log = { version = "0.4", default-features = false }
ring = { version = "0.16.20", default-features = false, features = ["alloc"] }
scale-info = { version = "2.10.0", default-features = false, features = ["derive"] }
serde = { default-features = false, version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", default-features = false, features = ["alloc"] }
webpki = { git = "https://github.com/rustls/webpki", version = "=0.102.0-alpha.3", rev = "da923ed", package = "rustls-webpki", default-features = false, features = ["alloc", "ring"] }
x509-cert = { default-features = false, version = "0.1.0", features = ["alloc"] }

frame-support = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.42" }
frame-system = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.42" }
pallet-timestamp = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.42" }
sp-core = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.42" }
sp-io = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.42" }
sp-runtime = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.42" }
sp-std = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.42" }

frame-benchmarking = { default-features = false, optional = true, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.42" }
pallet-balances = { default-features = false, optional = true, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.42" }

[dev-dependencies]
env_logger = "0.9.0"
externalities = { package = "sp-externalities", git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.42" }
frame-benchmarking = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.42" }
pallet-balances = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.42" }
sp-keyring = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.42" }

[features]
default = ["std"]
std = [
    "base64/std",
    "chrono/std",
    "der/std",
    "hex/std",
    "serde/std",
    "serde_json/std",
    "ring/std",
    "x509-cert/std",
    "codec/std",
    "log/std",
    "scale-info/std",
    "webpki/std",
    "frame-support/std",
    "frame-system/std",
    "sp-core/std",
    "sp-io/std",
    "sp-runtime/std",
    "sp-std/std",
    "pallet-timestamp/std",
    "pallet-balances?/std",
]
runtime-benchmarks = [
    "frame-benchmarking/runtime-benchmarks",
    "pallet-balances?/runtime-benchmarks",
    "pallet-timestamp/runtime-benchmarks",
]
try-runtime = ["frame-support/try-runtime"]
# workaround to cross crate boundary, see https://github.com/rust-lang/cargo/issues/8379
test-util = []
