[package]
name = "itp-hashing"
version = "0.9.0"
authors = ['Litentry Dev']
edition = "2021"

[dependencies]
# substrate
sp-core = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.39" }

[features]
default = ["std"]
std = []
