[package]
authors = ["Trust Computing GmbH <info@litentry.com>"]
edition = "2021"
name = "lc-assertion-build-v2"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# std dependencies
thiserror = { workspace = true, optional = true }

# sgx dependencies
sgx_tstd = { workspace = true, optional = true, features = ["net", "thread"] }
thiserror_sgx = { workspace = true, optional = true }

# no_std dependencies
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive"] }
log = { workspace = true }

# internal dependencies
itc-rest-client = { workspace = true }
itp-ocall-api = { workspace = true }
itp-stf-primitives = { workspace = true }
itp-types = { workspace = true }
itp-utils = { workspace = true }

# litentry
lc-assertion-build = { workspace = true }
lc-common = { workspace = true }
lc-credentials-v2 = { path = "../credentials-v2", default-features = false }
lc-service = { workspace = true }
lc-stf-task-sender = { path = "../stf-task/sender", default-features = false }
litentry-hex-utils = { workspace = true }
litentry-primitives = { workspace = true }

[dev-dependencies]
env_logger = { workspace = true }
lc-mock-server = { workspace = true }

[features]
default = ["std"]
sgx = [
    "sgx_tstd",
    "thiserror_sgx",
    "litentry-primitives/sgx",
    "lc-common/sgx",
    "lc-assertion-build/sgx",
    "lc-credentials-v2/sgx",
    "lc-service/sgx",
    "lc-stf-task-sender/sgx",
]
std = [
    "log/std",
    "itp-types/std",
    "itp-utils/std",
    "litentry-primitives/std",
    "lc-common/std",
    "lc-assertion-build/std",
    "lc-credentials-v2/std",
    "lc-service/std",
    "lc-stf-task-sender/std",
]
