[package]
name = "litentry-cli"
version = "0.0.1"
authors = ['Trust Computing GmbH <info@litentry.com>', 'Integritee AG <hello@integritee.network>']
edition = "2021"

[dependencies]
array-bytes = { workspace = true }
base58 = { workspace = true }
chrono = { workspace = true }
clap = { workspace = true }
codec = { version = "3.0.0", package = "parity-scale-codec", features = ["derive"] }
env_logger = { workspace = true }
hdrhistogram = { workspace = true }
hex = { workspace = true }
log = { workspace = true }
rand = { workspace = true }
rayon = { workspace = true }
regex = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sgx_crypto_helper = { workspace = true }
thiserror = { workspace = true }
urlencoding = { workspace = true }

# scs / integritee
pallet-evm = { optional = true, workspace = true }
# `default-features = false` to remove the jsonrpsee dependency.
substrate-api-client = { workspace = true }
substrate-client-keystore = { workspace = true }

# substrate dependencies
pallet-balances = { workspace = true }
sp-application-crypto = { workspace = true }
sp-core = { workspace = true }
sp-keyring = { workspace = true }
sp-keystore = { workspace = true }
sp-runtime = { workspace = true }

# local dependencies
ita-stf = { workspace = true }
itc-rpc-client = { workspace = true }
itp-node-api = { workspace = true }
itp-rpc = { workspace = true }
itp-sgx-crypto = { workspace = true }
itp-stf-primitives = { workspace = true }
itp-time-utils = { workspace = true }
itp-types = { workspace = true }
itp-utils = { workspace = true }
lc-credentials = { workspace = true }

# litentry
frame-metadata = { workspace = true }
ita-sgx-runtime = { workspace = true }
litentry-hex-utils = { workspace = true }
litentry-primitives = { workspace = true }
my-node-runtime = { package = "rococo-parachain-runtime", path = "../../runtime/rococo" }
pallet-teerex = { workspace = true }
scale-value = { workspace = true }
sp-core-hashing = { workspace = true }

[features]
default = []
evm = ["ita-stf/evm_std", "pallet-evm"]
sidechain = []
offchain-worker = []
production = []
# dcap feature flag is not used in this crate, but for easier build purposes only it present here as well
dcap = []
