[package]
authors = ["Integritee AG <hello@integritee.network>"]
edition = "2021"
homepage = "https://integritee.network/"
license = "Apache-2.0"
name = "sidechain-primitives"
repository = "https://github.com/integritee-network/pallets/"
version = "0.1.0"

[dependencies]
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive", "full"] }
scale-info = { version = "2.9.0", default-features = false, features = ["derive"] }
serde = { version = "1.0", default-features = false }


# substrate dependencies
sp-core = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.39" }
sp-io = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.39" }
sp-runtime = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.39" }
sp-std = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.39" }


[features]
default = ["std", "full_crypto"]
full_crypto = [
    "sp-core/full_crypto",
]
std = [
    "codec/std",
    "scale-info/std",
    "serde/std",
    # substrate
    "sp-core/std",
    "sp-io/std",
    "sp-runtime/std",
    "sp-std/std",
]
