[package]
name = "itp-teerex-storage"
version = "0.9.0"
authors = ['Trust Computing GmbH <info@litentry.com>', 'Integritee AG <hello@integritee.network>']
edition = "2021"

[dependencies]
sp-std = { workspace = true }

#local deps
itp-storage = { workspace = true }

[features]
default = ["std"]
std = [
    "sp-std/std",
    "itp-storage/std",
]
