[package]
authors = ['Litentry Dev']
edition = "2021"
homepage = 'https://litentry.com/'
license = "Apache-2.0"
name = "teeracle-primitives"
repository = 'https://github.com/litentry/litentry-parachain'
version = "0.1.0"

[dependencies]
# local
common-primitives = { path = "../common", default-features = false }

# encointer
substrate-fixed = { tag = "v0.5.9", default-features = false, git = "https://github.com/encointer/substrate-fixed.git" }

# substrate
sp-std = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.39" }


[features]
default = ["std"]
std = [
    "common-primitives/std",
    "substrate-fixed/std",
    "sp-std/std",
]
