[package]
name = "itp-node-api-metadata"
version = "0.9.0"
authors = ['Trust Computing GmbH <info@litentry.com>', 'Integritee AG <hello@integritee.network>']
edition = "2021"

[dependencies]
# crates.io
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive"] }
derive_more = { version = "0.99.5" }

# local
itp-api-client-types = { default-features = false, path = "../api-client-types" }

# substrate
sp-core = { git = "https://github.com/paritytech/substrate.git", default-features = false, branch = "polkadot-v0.9.42" }

# scs
substrate-api-client = { default-features = false, git = "https://github.com/scs/substrate-api-client.git", branch = "polkadot-v0.9.42-tag-v0.10.0" }

# litentry
base58 = "0.2"
hex = { version = "0.4", default-features = false }
itp-sgx-runtime-primitives = { path = "../../sgx-runtime-primitives", default-features = false }
itp-types = { path = "../../types", default-features = false }
litentry-primitives = { path = "../../../litentry/primitives", default-features = false }
log = { version = "0.4", default-features = false }
primitive-types = { version = "0.12.1", default-features = false, features = ["codec"] }
substrate-fixed = { tag = "v0.5.9", default-features = false, git = "https://github.com/encointer/substrate-fixed.git", optional = true }


[features]
default = ["std"]
std = [
    "codec/std",
    "itp-api-client-types/std",
    "sp-core/std",
    "substrate-api-client/std",
    # litentry
    "primitive-types/std",
    "substrate-fixed/std",
    "litentry-primitives/std",
    "itp-types/std",
    "itp-sgx-runtime-primitives/std",
]

# used for unit testing only!
mocks = []
