[package]
authors = ["Integritee AG <hello@integritee.network>"]
edition = "2021"
name = "itp-node-api-metadata"
version = "0.9.0"

[dependencies]
# crates.io
base58 = "0.2"
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive"] }
derive_more = { version = "0.99.5" }
hex = { version = "0.4", default-features = false }
log = { version = "0.4", default-features = false }
primitive-types = { version = "0.12.1", default-features = false, features = ["codec"] }

# substrate
sp-core = { git = "https://github.com/paritytech/substrate.git", default-features = false, branch = "polkadot-v0.9.39" }

# scs
substrate-api-client = { default-features = false, git = "https://github.com/scs/substrate-api-client.git", branch = "polkadot-v0.9.39-tag-v0.7.0" }
substrate-fixed = { tag = "v0.5.9", default-features = false, git = "https://github.com/encointer/substrate-fixed.git", optional = true }

# litentry
litentry-primitives = { path = "../../../litentry/primitives", default-features = false }

# local
itp-sgx-runtime-primitives = { path = "../../sgx-runtime-primitives", default-features = false }
itp-types = { path = "../../types", default-features = false }


[features]
default = ["std"]
std = [
    "codec/std",
    "primitive-types/std",
    "sp-core/std",
    "substrate-api-client/std",
    "substrate-fixed/std",
    "litentry-primitives/std",
    "itp-types/std",
    "itp-sgx-runtime-primitives/std",
]

# used for unit testing only!
mocks = []
