[package]
name = "itp-node-api-metadata"
version = "0.9.0"
authors = ['Trust Computing GmbH <info@litentry.com>', 'Integritee AG <hello@integritee.network>']
edition = "2021"

[dependencies]
# crates.io
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive"] }
derive_more = { workspace = true }

# local
itp-api-client-types = { workspace = true }
itp-stf-primitives = { workspace = true }

# substrate
sp-core = { workspace = true }

[features]
default = ["std"]
std = [
    "codec/std",
    "itp-api-client-types/std",
    "sp-core/std",
    "itp-stf-primitives/std",
]

# used for unit testing only!
mocks = []
