[package]
authors = ["Trust Computing GmbH <info@litentry.com>"]
edition = '2021'
name = 'core-primitives'
version = '0.9.12'

[dependencies]
parity-scale-codec = { workspace = true }
serde = { version = "1.0", default-features = false, features = ["alloc", "derive"] }
strum = { version = "0.26", default-features = false }
strum_macros = { version = "0.26", default-features = false }

frame-support = { workspace = true }
pallet-evm = { workspace = true }
ring = { workspace = true }
scale-info = { workspace = true }
sp-core = { workspace = true }
sp-io = { workspace = true }
sp-runtime = { workspace = true }
sp-std = { workspace = true }

litentry-hex-utils = { path = "../hex", default-features = false }
litentry-macros = { path = "macros" }
litentry-proc-macros = { path = "proc-macros" }

[features]
default = ["std"]
std = [
    "serde/std",
    "strum/std",
    "parity-scale-codec/std",
    "scale-info/std",
    "frame-support/std",
    "sp-core/std",
    "sp-runtime/std",
    "sp-std/std",
    "sp-io/std",
    "ring/std",
    "pallet-evm/std",
]
production = [
    "litentry-macros/production",
]
