[package]
authors = ["Trust Computing GmbH <info@litentry.com>"]
edition = "2021"
name = "lc-identity-verification"
version = "0.1.0"

[dependencies]
# std dependencies
hex = { workspace = true, optional = true }

# sgx dependencies
futures_sgx = { workspace = true, optional = true }
hex-sgx = { workspace = true, optional = true }
http-sgx = { workspace = true, optional = true }
http_req-sgx = { workspace = true, optional = true }
sgx_tstd = { workspace = true, features = ["net", "thread"], optional = true }
thiserror_sgx = { workspace = true, optional = true }
url_sgx = { workspace = true, optional = true }

# no_std dependencies
log = { workspace = true }

# internal dependencies
itp-sgx-crypto = { workspace = true }

frame-support = { workspace = true }

lc-data-providers = { workspace = true }
lc-stf-task-sender = { workspace = true }
litentry-primitives = { workspace = true }

[features]
default = ["std"]
sgx = [
    "futures_sgx",
    "hex-sgx",
    "http-sgx",
    "http_req-sgx",
    "sgx_tstd",
    "thiserror_sgx",
    "url_sgx",
    "itp-sgx-crypto/sgx",
    "lc-data-providers/sgx",
    "litentry-primitives/sgx",
    "lc-stf-task-sender/sgx",
]
std = [
    "hex",
    "log/std",
    "itp-sgx-crypto/std",
    "frame-support/std",
    "lc-data-providers/std",
    "litentry-primitives/std",
    "lc-stf-task-sender/std",
]
