[package]
name = "itp-rpc"
version = "0.9.0"
authors = ['Trust Computing GmbH <info@litentry.com>', 'Integritee AG <hello@integritee.network>']
edition = "2021"

[dependencies]
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive"] }
itp-types = { workspace = true }
serde = { workspace = true, features = ["alloc", "derive"] }
serde_json = { workspace = true, features = ["alloc"] }

# sgx deps
sgx_tstd = { workspace = true, optional = true }

[features]
default = ["std"]
std = [
    "codec/std",
    "itp-types/std",
    "serde/std",
    "serde_json/std",
]
sgx = [
    "sgx_tstd",
]
