[package]
name = "itp-node-api-factory"
version = "0.9.0"
authors = ['Litentry Technologies GmbH <info@litentry.com> and Integritee AG <hello@integritee.network>']
edition = "2021"

[dependencies]
thiserror = { version = "1.0" }

# substrate
sp-core = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.39" }

# local
itp-api-client-types = { path = "../api-client-types" }
