[package]
name = "itc-tls-websocket-server"
version = "0.9.0"
authors = ['Trust Computing GmbH <info@litentry.com>', 'Integritee AG <hello@integritee.network>']
edition = "2021"

[dependencies]
bit-vec = { version = "0.6", default-features = false }
chrono = { version = "0.4.19", default-features = false, features = ["alloc"] }
rcgen = { package = "rcgen", default-features = false, git = "https://github.com/integritee-network/rcgen" }

# sgx dependencies
sgx_crypto_helper = { branch = "master", git = "https://github.com/apache/teaclave-sgx-sdk.git", default-features = false }
sgx_tstd = { optional = true, features = ["net", "thread"], git = "https://github.com/apache/teaclave-sgx-sdk.git", branch = "master" }
sgx_types = { branch = "master", git = "https://github.com/apache/teaclave-sgx-sdk.git", optional = true }

# sgx enabled external libraries
mio-extras = { optional = true, default-features = false, git = "https://github.com/integritee-network/mio-extras-sgx", rev = "963234b" }
mio_sgx = { package = "mio", optional = true, git = "https://github.com/mesalock-linux/mio-sgx", tag = "sgx_1.1.3" }
rand_sgx = { package = "rand", optional = true, git = "https://github.com/mesalock-linux/rand-sgx", tag = "v0.7.3_sgx1.1.3" }
rustls_sgx = { package = "rustls", optional = true, git = "https://github.com/mesalock-linux/rustls", branch = "mesalock_sgx" }
serde-big-array-sgx = { package = "serde-big-array", git = "https://github.com/mesalock-linux/serde-big-array-sgx", optional = true }
serde-sgx = { package = "serde", git = "https://github.com/mesalock-linux/serde-sgx", optional = true }
serde_derive-sgx = { package = "serde_derive", git = "https://github.com/mesalock-linux/serde-sgx", optional = true }
serde_json-sgx = { package = "serde_json", git = "https://github.com/mesalock-linux/serde-json-sgx", optional = true }
thiserror_sgx = { package = "thiserror", optional = true, git = "https://github.com/mesalock-linux/thiserror-sgx", tag = "sgx_1.1.3" }
tungstenite_sgx = { package = "tungstenite", optional = true, features = ["rustls-tls-webpki-roots"], git = "https://github.com/integritee-network/tungstenite-rs-sgx", branch = "sgx-experimental" }
webpki_sgx = { package = "webpki", optional = true, git = "https://github.com/mesalock-linux/webpki", branch = "mesalock_sgx" }
yasna_sgx = { package = "yasna", optional = true, default-features = false, features = ["bit-vec", "num-bigint", "chrono", "mesalock_sgx"], git = "https://github.com/mesalock-linux/yasna.rs-sgx", rev = "sgx_1.1.3" }

# std compatible external libraries (make sure these versions match with the sgx-enabled ones above)
mio = { version = "0.6.14", optional = true }
once_cell = { version = "1.18", optional = true }
rand = { version = "0.7.3", optional = true }
rustls = { version = "0.19", optional = true }
serde = { version = "1.0", optional = true }
serde-big-array = { version = "0.3", optional = true }
serde_derive = { version = "1.0", optional = true }
serde_json = { version = "1.0", optional = true }
thiserror = { version = "1.0", optional = true }
tungstenite = { version = "0.15.0", optional = true, features = ["rustls-tls-webpki-roots"] }
webpki = { version = "0.21", optional = true }
yasna = { version = "0.4", optional = true, features = ["bit-vec", "num-bigint", "chrono", "std"] }

# Substrate dependencies
sp-core = { default-features = false, features = ["full_crypto"], git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.42" }

# no-std compatible libraries
aes-gcm = "0.10"
log = { version = "0.4", default-features = false }
rand_core = "0.6.4"
rsa = { version = "0.9.3", default-features = false, optional = true }

[dev-dependencies]
env_logger = "0.9.0"
once_cell = "1.18"
rustls = { version = "0.19", features = ["dangerous_configuration"] }
url = { version = "2.0.0" }


[features]
default = ["std", "rsa"]
sgx = [
    "mio-extras/sgx",
    "mio_sgx",
    "rand_sgx",
    "rcgen/sgx",
    "rcgen/pem_sgx",
    "rsa",
    "rustls_sgx",
    "serde-sgx",
    "serde_derive-sgx",
    "serde-big-array-sgx",
    "serde_json-sgx",
    "sgx_crypto_helper/mesalock_sgx",
    "sgx_tstd",
    "sgx_types",
    "thiserror_sgx",
    "tungstenite_sgx",
    "webpki_sgx",
    "yasna_sgx",
]
std = [
    "mio",
    "mio-extras/std",
    "rand",
    "rcgen/std",
    "rcgen/pem",
    "rsa",
    "rsa/default",
    "rustls",
    "serde",
    "serde_derive",
    "serde-big-array",
    "serde_json",
    "sgx_crypto_helper/ucrypto_help",
    "thiserror",
    "tungstenite",
    "webpki",
    "yasna",
    "log/std",
]
rsa = [
    "dep:rsa",
]
mocks = ["once_cell"]
