[package]
name = "itc-tls-websocket-server"
version = "0.9.0"
authors = ['Trust Computing GmbH <info@litentry.com>', 'Integritee AG <hello@integritee.network>']
edition = "2021"

[dependencies]
bit-vec = { workspace = true }
chrono = { workspace = true }
rcgen = { workspace = true }

# sgx dependencies
sgx_tstd = { optional = true, features = ["net", "thread"], workspace = true }

# sgx enabled external libraries
mio-extras = { optional = true, workspace = true }
mio_sgx = { optional = true, workspace = true }
rustls_sgx = { optional = true, workspace = true }
thiserror_sgx = { optional = true, workspace = true }
tungstenite_sgx = { optional = true, workspace = true }
webpki_sgx = { optional = true, workspace = true }
yasna_sgx = { optional = true, workspace = true }

# std compatible external libraries (make sure these versions match with the sgx-enabled ones above)
mio = { workspace = true, optional = true }
rustls = { workspace = true, optional = true }
thiserror = { workspace = true, optional = true }
tungstenite = { workspace = true, optional = true }
webpki = { workspace = true, optional = true }
yasna = { workspace = true, optional = true }

# Substrate dependencies
sp-core = { workspace = true }

# no-std compatible libraries
log = { workspace = true }

[dev-dependencies]
env_logger = { workspace = true }
rustls = { workspace = true }
url = { workspace = true }


[features]
default = ["std"]
sgx = [
    "mio-extras/sgx",
    "mio_sgx",
    "rcgen/sgx",
    "rcgen/pem_sgx",
    "rustls_sgx",
    "sgx_tstd",
    "thiserror_sgx",
    "tungstenite_sgx",
    "webpki_sgx",
    "yasna_sgx",
]
std = [
    "mio",
    "mio-extras/std",
    "rcgen/std",
    "rcgen/pem",
    "rustls",
    "thiserror",
    "tungstenite",
    "webpki",
    "yasna",
    "log/std",
]
mocks = []
