[package]
name = "itc-direct-rpc-client"
version = "0.1.0"
authors = ['Trust Computing GmbH <info@litentry.com>']
edition = "2021"

[dependencies]
# sgx dependencies
rustls_sgx = { workspace = true, optional = true }
sgx_tstd = { workspace = true, optional = true }
tungstenite_sgx = { workspace = true, optional = true }
url_sgx = { workspace = true, optional = true }
webpki_sgx = { workspace = true, optional = true }

# no-std dependencies
codec = { workspace = true }
log = { workspace = true }
serde_json = { workspace = true }

# std dependencies
rustls = { workspace = true, optional = true }
tungstenite = { workspace = true, optional = true }
url = { workspace = true, optional = true }
webpki = { workspace = true, optional = true }

# local dependencies
itp-rpc = { workspace = true }
itp-types = { workspace = true }
itp-utils = { workspace = true }
litentry-primitives = { workspace = true }

[features]
default = ["std"]
sgx = [
    "webpki_sgx",
    "url_sgx",
    "tungstenite_sgx",
    "rustls_sgx",
    "sgx_tstd",
    "itp-rpc/sgx",
    "litentry-primitives/sgx",
]
std = [
    "rustls",
    "webpki",
    "tungstenite",
    "url",
    "itp-rpc/std",
    "itp-types/std",
    "itp-utils/std",
    "log/std",
    "litentry-primitives/std",
]
