[package]
name = "itc-direct-rpc-client"
version = "0.1.0"
authors = ['Trust Computing GmbH <info@litentry.com>']
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false }
itp-rpc = { path = "../../core-primitives/rpc", default-features = false }
itp-sgx-crypto = { path = "../../core-primitives/sgx/crypto", default-features = false }
itp-types = { path = "../../core-primitives/types", default-features = false }
itp-utils = { path = "../../core-primitives/utils", default-features = false }

log = { version = "0.4", default-features = false }

rustls = { version = "0.19", optional = true, features = ["dangerous_configuration"] }
rustls_sgx = { package = "rustls", optional = true, git = "https://github.com/mesalock-linux/rustls", tag = "sgx_1.1.3", features = ["dangerous_configuration"] }

serde = { version = "1.0", default-features = false, features = ["alloc", "derive"] }
serde_json = { version = "1.0", default-features = false }

sgx-crypto-helper = { branch = "master", git = "https://github.com/apache/teaclave-sgx-sdk.git", package = "sgx_crypto_helper", default-features = false }
sgx_tstd = { branch = "master", git = "https://github.com/apache/teaclave-sgx-sdk.git", optional = true }
tungstenite = { version = "0.15.0", optional = true, features = ["rustls-tls-webpki-roots"] }
tungstenite_sgx = { package = "tungstenite", optional = true, git = "https://github.com/integritee-network/tungstenite-rs-sgx", branch = "sgx-experimental", features = ["rustls-tls-webpki-roots"] }

url = { version = "2.0.0", optional = true }
url_sgx = { package = "url", optional = true, git = "https://github.com/mesalock-linux/rust-url-sgx", tag = "sgx_1.1.3" }

webpki = { version = "0.21", optional = true }
webpki_sgx = { package = "webpki", optional = true, git = "https://github.com/mesalock-linux/webpki", branch = "mesalock_sgx" }

[features]
default = ["std"]
sgx = [
    "webpki_sgx",
    "url_sgx",
    "tungstenite_sgx",
    "rustls_sgx",
    "sgx_tstd",
    "itp-rpc/sgx",
    "itp-sgx-crypto/sgx",
    "itp-utils/sgx",
]
std = [
    "rustls",
    "webpki",
    "tungstenite",
    "url",
    "itp-rpc/std",
    "itp-sgx-crypto/std",
    "itp-types/std",
    "itp-utils/std",
    "log/std",
]
