[package]
name = "itc-rest-client"
version = "0.9.0"
authors = ['Trust Computing GmbH <info@litentry.com>', 'Integritee AG <hello@integritee.network>']
edition = "2021"

[dependencies]
# std dependencies
http = { version = "0.2", optional = true }
http_req = { optional = true, workspace = true }
thiserror = { workspace = true, optional = true }
url = { workspace = true, optional = true }

# sgx dependencies
http-sgx = { workspace = true, optional = true }
http_req-sgx = { optional = true, workspace = true }
sgx_tstd = { workspace = true, optional = true, features = ["net", "thread"] }
thiserror_sgx = { workspace = true, optional = true }
url_sgx = { workspace = true, optional = true }

# no_std dependencies
base64 = { workspace = true }
log = { workspace = true }
serde = { workspace = true, features = ["derive", "alloc"] }
serde_json = { workspace = true, features = ["alloc"] }

[features]
default = ["std"]
std = [
    # std only
    "http",
    "http_req",
    "thiserror",
    "url",
    # no_std
    "base64/std",
    "serde/std",
    "serde_json/std",
    "log/std",
]
sgx = [
    "http-sgx",
    "http_req-sgx",
    "sgx_tstd",
    "thiserror_sgx",
    "url_sgx",
]
