[package]
authors = ["Integritee AG <hello@integritee.network>"]
edition = "2021"
name = "itp-api-client-extensions"
version = "0.9.0"

[dependencies]
# crates.io
codec = { package = "parity-scale-codec", version = "3.0.0", features = ["derive"] }
hex = "0.4"
thiserror = { version = "1.0" }

# substrate
sp-core = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.39" }
sp-finality-grandpa = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.39" }
sp-runtime = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.39" }

# scs
substrate-api-client = { git = "https://github.com/scs/substrate-api-client.git", branch = "polkadot-v0.9.39-tag-v0.7.0" }

# local deps
itp-types = { path = "../../types" }

[features]
# used for unit testing only!
mocks = []
