[package]
name = "itp-api-client-extensions"
version = "0.9.0"
authors = ['Trust Computing GmbH <info@litentry.com>', 'Integritee AG <hello@integritee.network>']
edition = "2021"

[dependencies]

# substrate
sp-consensus-grandpa = { workspace = true }
sp-runtime = { workspace = true }

# scs
# `default-features = false` to remove the jsonrpsee dependency.
substrate-api-client = { workspace = true }

# local deps
itp-api-client-types = { workspace = true }
itp-types = { workspace = true }

# litentry
hex = { workspace = true }
sp-core = { workspace = true }

[features]
# used for unit testing only!
mocks = []
