[package]
name = "itc-direct-rpc-server"
version = "0.9.0"
authors = ['Trust Computing GmbH <info@litentry.com>', 'Integritee AG <hello@integritee.network>']
edition = "2021"

[dependencies]
# sgx dependencies
sgx_tstd = { workspace = true, optional = true, features = ["net", "thread"] }

# no-std dependencies
codec = { workspace = true, features = ["derive"] }
log = { workspace = true }
serde_json = { workspace = true, features = ["alloc"] }
sp-runtime = { workspace = true }

# local
itc-tls-websocket-server = { workspace = true }
itp-rpc = { workspace = true }
itp-types = { workspace = true }
itp-utils = { workspace = true }

# sgx enabled external libraries
jsonrpc-core_sgx = { workspace = true, optional = true }
thiserror_sgx = { workspace = true, optional = true }

# std compatible external libraries (make sure these versions match with the sgx-enabled ones above)
jsonrpc-core = { workspace = true, optional = true }
thiserror = { workspace = true, optional = true }

[features]
default = ["std"]
std = [
    # no-std dependencies
    "codec/std",
    "log/std",
    "serde_json/std",
    "sp-runtime/std",
    # integritee dependencies
    "itp-types/std",
    # local
    "itc-tls-websocket-server/std",
    "itp-rpc/std",
    # optional ones
    "jsonrpc-core",
    "thiserror",
]
sgx = [
    "itc-tls-websocket-server/sgx",
    "itp-rpc/sgx",
    "jsonrpc-core_sgx",
    "sgx_tstd",
    "thiserror_sgx",
]
mocks = []
