[package]
authors = ['Litentry Technologies GmbH <info@litentry.com>']
edition = "2021"
homepage = 'https://litentry.com/'
license = "Apache-2.0"
name = "common-primitives"
repository = 'https://github.com/litentry/litentry-parachain'
version = "0.1.0"

[dependencies]

# substrate deps
sp-std = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.39" }

[features]
default = ["std"]
std = [
    "sp-std/std",
]
