[package]
name = "itc-offchain-worker-executor"
version = "0.9.0"
authors = ['Trust Computing GmbH <info@litentry.com>', 'Integritee AG <hello@integritee.network>']
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
codec = { workspace = true, features = ["derive"] }
# sgx dependencies
sgx_tstd = { workspace = true, optional = true }

# sgx enabled external libraries
thiserror_sgx = { workspace = true, optional = true }

# std compatible external libraries (make sure these versions match with the sgx-enabled ones above)
thiserror = { workspace = true, optional = true }

# local dependencies
itc-parentchain-light-client = { workspace = true }
itp-extrinsics-factory = { workspace = true }
itp-stf-executor = { workspace = true }
itp-stf-interface = { workspace = true }
itp-stf-primitives = { workspace = true }
itp-stf-state-handler = { workspace = true }
itp-top-pool-author = { workspace = true }
itp-types = { workspace = true }

# Substrate dependencies
sp-runtime = { workspace = true }

# no-std compatible libraries
log = { workspace = true }

[dev-dependencies]
itp-stf-primitives = { workspace = true }
codec = { workspace = true, features = ["derive"] }
itc-parentchain-light-client = { workspace = true, features = ["mocks"] }
itp-extrinsics-factory = { workspace = true, features = ["mocks"] }
itp-stf-executor = { workspace = true, features = ["mocks"] }
itp-test = { workspace = true }
itp-top-pool-author = { workspace = true, features = ["mocks"] }
itp-stf-interface = { workspace = true, features = ["mocks"] }
itp-sgx-externalities = { workspace = true }
sp-core = { workspace = true }

[features]
default = ["std"]
std = [
    "itc-parentchain-light-client/std",
    "itp-extrinsics-factory/std",
    "itp-stf-executor/std",
    "itp-stf-interface/std",
    "itp-stf-primitives/std",
    "itp-stf-state-handler/std",
    "itp-top-pool-author/std",
    "itp-types/std",
    "sp-runtime/std",
    "thiserror",
]
sgx = [
    "itc-parentchain-light-client/sgx",
    "itp-extrinsics-factory/sgx",
    "itp-stf-executor/sgx",
    "itp-stf-state-handler/sgx",
    "itp-top-pool-author/sgx",
    "sgx_tstd",
    "thiserror_sgx",
]
