[package]
name = "itp-enclave-bridge-storage"
version = "0.9.0"
authors = ["Integritee AG <hello@integritee.network>"]
edition = "2021"

[dependencies]
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive"] }
sp-std = { workspace = true }

#local deps
itp-storage = { workspace = true }

[features]
default = ["std"]
std = [
    "codec/std",
    "sp-std/std",
    "itp-storage/std",
]
