[package]
name = "itp-api-client-types"
version = "0.9.0"
authors = ['Trust Computing GmbH <info@litentry.com>', 'Integritee AG <hello@integritee.network>']
edition = "2021"

[dependencies]
# scs
substrate-api-client = { workspace = true, features = ["sync-api"] }

# substrate
sp-runtime = { workspace = true }

# local
itp-types = { workspace = true }

# litentry
my-node-runtime = { package = "rococo-parachain-runtime", path = "../../../../runtime/rococo", optional = true }

[features]
default = ["std"]
std = [
    "itp-types/std",
    "substrate-api-client/std",
    "substrate-api-client/tungstenite-client",
    "sp-runtime/std",
    "my-node-runtime/std",
]
