[package]
name = "itp-api-client-types"
version = "0.9.0"
authors = ['Trust Computing GmbH <info@litentry.com>', 'Integritee AG <hello@integritee.network>']
edition = "2021"

[dependencies]
# scs
substrate-api-client = { default-features = false, features = ["sync-api"], git = "https://github.com/scs/substrate-api-client.git", branch = "polkadot-v0.9.42-tag-v0.14.0" }

# substrate
sp-runtime = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.42" }

# local
itp-types = { default-features = false, path = "../../types" }

# litentry
my-node-runtime = { package = "rococo-parachain-runtime", path = "../../../../runtime/rococo", optional = true }

[features]
default = ["std"]
std = [
    "itp-types/std",
    "substrate-api-client/std",
    "substrate-api-client/tungstenite-client",
    "sp-runtime/std",
    "my-node-runtime/std",
]
