[package]
name = "itp-sgx-io"
version = "0.8.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

# sgx deps
sgx_tprotected_fs = { git = "https://github.com/apache/incubator-teaclave-sgx-sdk", branch = "v2.0.0-preview", optional = true }
sgx_tstd = { git = "https://github.com/apache/incubator-teaclave-sgx-sdk", branch = "v2.0.0-preview", features = ["untrusted_fs"], optional = true }

[features]
default = ["std"]
std = []
sgx = [
    "sgx_tprotected_fs",
    "sgx_tstd",
]
