[package]
authors = ["Trust Computing GmbH <info@litentry.com>"]
edition = "2021"
name = "lc-credentials"
version = "0.1.0"

[dependencies]
# std dependencies
chrono = { workspace = true, features = ["alloc"] }
hex = { workspace = true, optional = true }
rust-base58 = { workspace = true, optional = true }
scale-info = { workspace = true, features = ["derive"] }
thiserror = { workspace = true, optional = true }

# sgx dependencies
chrono_sgx = { workspace = true, optional = true }
hex-sgx = { workspace = true, optional = true }
rand-sgx = { workspace = true, optional = true }
rust-base58-sgx = { workspace = true, optional = true }
serde_json_sgx = { workspace = true, optional = true }
sgx_tstd = { workspace = true, optional = true, features = ["net", "thread"] }
thiserror_sgx = { workspace = true, optional = true }

# no_std dependencies
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive"] }
log = { workspace = true }
rand = { workspace = true, optional = true }
serde = { workspace = true, features = ["derive", "alloc"] }
serde_json = { workspace = true, features = ["alloc"] }

# internal dependencies
itp-stf-primitives = { workspace = true }
itp-time-utils = { workspace = true }
itp-types = { workspace = true }
itp-utils = { workspace = true }
sp-core = { workspace = true }

# litentry
lc-data-providers = { workspace = true }
litentry-primitives = { workspace = true }

[features]
default = ["std"]
sgx = [
    "rust-base58-sgx",
    "hex-sgx",
    "sgx_tstd",
    "thiserror_sgx",
    "chrono_sgx",
    "serde_json_sgx",
    "litentry-primitives/sgx",
    "rand-sgx",
    "itp-time-utils/sgx",
    "lc-data-providers/sgx",
]
std = [
    "rust-base58",
    "hex",
    "log/std",
    "serde/std",
    "serde_json/std",
    "thiserror",
    "itp-types/std",
    "itp-utils/std",
    "litentry-primitives/std",
    "rand",
    "itp-time-utils/std",
    "lc-data-providers/std",
]
