[package]
authors = ["Litentry Dev"]
edition = "2021"
name = "lc-credentials"
version = "0.1.0"

[dependencies]
# std dependencies
chrono = { version = "0.4.19", default-features = false, features = ["alloc"] }
futures = { version = "0.3.8", optional = true }
hex = { version = "0.4.3", optional = true }
http = { version = "0.2", optional = true }
http_req = { optional = true, features = ["rust-tls"], branch = "master", git = "https://github.com/integritee-network/http_req" }
rust-base58 = { package = "rust-base58", version = "0.0.4", optional = true }
scale-info = { version = "2.1.1", default-features = false, features = ["derive"] }
thiserror = { version = "1.0.38", optional = true }
url = { version = "2.0.0", optional = true }

# sgx dependencies
chrono_sgx = { package = "chrono", git = "https://github.com/mesalock-linux/chrono-sgx", optional = true }
futures_sgx = { package = "futures", git = "https://github.com/mesalock-linux/futures-rs-sgx", optional = true }
hex-sgx = { package = "hex", git = "https://github.com/mesalock-linux/rust-hex-sgx", tag = "sgx_1.1.3", features = ["sgx_tstd"], optional = true }
http-sgx = { package = "http", git = "https://github.com/integritee-network/http-sgx.git", branch = "sgx-experimental", optional = true }
http_req-sgx = { optional = true, default-features = false, features = ["rust-tls", "sgx"], package = "http_req", git = "https://github.com/integritee-network/http_req" }
rand-sgx = { package = "rand", git = "https://github.com/mesalock-linux/rand-sgx", tag = "sgx_1.1.3", features = ["sgx_tstd"], optional = true }
rust-base58-sgx = { git = "https://github.com/mesalock-linux/rust-base58-sgx", optional = true, package = "rust-base58", features = ["mesalock_sgx"] }
serde_json_sgx = { package = "serde_json", tag = "sgx_1.1.3", git = "https://github.com/mesalock-linux/serde-json-sgx", optional = true }
sgx_tstd = { branch = "master", git = "https://github.com/apache/teaclave-sgx-sdk.git", optional = true, features = ["net", "thread"] }
thiserror_sgx = { package = "thiserror", git = "https://github.com/mesalock-linux/thiserror-sgx", tag = "sgx_1.1.3", optional = true }
url_sgx = { package = "url", git = "https://github.com/mesalock-linux/rust-url-sgx", tag = "sgx_1.1.3", optional = true }

# no_std dependencies
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive"] }
log = { version = "0.4", default-features = false }
rand = { version = "0.7", optional = true }
serde = { version = "1.0", default-features = false, features = ["derive", "alloc"] }
serde_json = { version = "1.0", default-features = false, features = ["alloc"] }

# internal dependencies
itp-ocall-api = { path = "../../../core-primitives/ocall-api", default-features = false }
itp-sgx-crypto = { path = "../../../core-primitives/sgx/crypto", default-features = false }
itp-sgx-externalities = { path = "../../../core-primitives/substrate-sgx/externalities", default-features = false }
itp-stf-primitives = { default-features = false, path = "../../../core-primitives/stf-primitives" }
itp-types = { path = "../../../core-primitives/types", default-features = false }
itp-utils = { path = "../../../core-primitives/utils", default-features = false }
sp-core = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.37", default-features = false }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.37", default-features = false }
sp-std = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.37", default-features = false }

# litentry
litentry-primitives = { path = "../../primitives", default-features = false }

[features]
default = ["std"]
sgx = [
    "rust-base58-sgx",
    "futures_sgx",
    "hex-sgx",
    "http-sgx",
    "http_req-sgx",
    "sgx_tstd",
    "thiserror_sgx",
    "url_sgx",
    "chrono_sgx",
    "serde_json_sgx",
    "itp-sgx-externalities/sgx",
    "litentry-primitives/sgx",
    "rand-sgx",
]
std = [
    "rust-base58",
    "futures",
    "hex",
    "http",
    "http_req",
    "log/std",
    "serde/std",
    "serde_json/std",
    "thiserror",
    "url",
    "itp-types/std",
    "itp-utils/std",
    "itp-sgx-externalities/std",
    "sp-std/std",
    "sp-runtime/std",
    "litentry-primitives/std",
    "rand",
]
