[package]
name = "itp-enclave-scheduled"
version = "0.8.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = { version = "0.4", default-features = false }

# sgx deps
serde = { package = "serde", git = "https://github.com/mesalock-linux/serde-sgx", features = ["derive"], optional = true }
serde_json = { package = "serde_json", tag = "sgx_1.1.3", git = "https://github.com/mesalock-linux/serde-json-sgx", optional = true }
sgx_tstd = { branch = "master", git = "https://github.com/apache/teaclave-sgx-sdk.git", optional = true }

# local dependencies
itp-settings = { path = "../../settings" }
itp-sgx-io = { path = "../io", default-features = false }
itp-types = { default-features = false, path = "../../types" }
litentry-primitives = { path = "../../../litentry/primitives", default-features = false }


[features]
default = ["std"]
sgx = ["sgx_tstd", "serde", "serde_json", "itp-sgx-io/sgx"]
std = ["itp-sgx-io/std"]
