[package]
name = "itp-stf-state-observer"
version = "0.9.0"
authors = ['Trust Computing GmbH <info@litentry.com>', 'Integritee AG <hello@integritee.network>']
edition = "2021"

[dependencies]
sgx_tstd = { workspace = true, optional = true }

# local deps
itp-types = { workspace = true }

# sgx enabled external libraries
thiserror_sgx = { workspace = true, optional = true }

# std compatible external libraries (make sure these versions match with the sgx-enabled ones above)
log = { workspace = true }
thiserror = { workspace = true, optional = true }

[features]
default = ["std"]
std = [
    "itp-types/std",
    "log/std",
    "thiserror",
]
sgx = [
    "sgx_tstd",
    "thiserror_sgx",
]
mocks = []
