[package]
authors = ["Trust Computing GmbH <info@litentry.com>"]
edition = '2021'
name = 'precompile-utils'
version = '0.9.17'

[dependencies]
assert_matches = { workspace = true }
impl-trait-for-tuples = { workspace = true }
log = { workspace = true }
num_enum = { workspace = true }
parity-scale-codec = { workspace = true }
sha3 = { workspace = true }
similar-asserts = { workspace = true, optional = true }

precompile-utils-macro = { path = "macro" }

fp-evm = { workspace = true }
frame-support = { workspace = true }
frame-system = { workspace = true }
pallet-evm = { workspace = true }
sp-core = { workspace = true }
sp-io = { workspace = true }
sp-runtime = { workspace = true }
sp-std = { workspace = true }

# There's a problem with --all-features when this is moved under dev-deps
evm = { git = "https://github.com/rust-blockchain/evm", rev = "b7b82c7e1fc57b7449d6dfa6826600de37cc1e65", default-features = false, optional = true }

[dev-dependencies]
hex-literal = { workspace = true }

[features]
default = ["std"]
std = [
    "evm/std",
    "parity-scale-codec/std",
    "fp-evm/std",
    "frame-support/std",
    "frame-system/std",
    "pallet-evm/std",
    "sp-core/std",
    "sp-io/std",
    "sp-runtime/std",
    "sp-std/std",
]
testing = ["similar-asserts", "std"]
