[package]
authors = ["Trust Computing GmbH <info@litentry.com>"]
edition = '2021'
name = 'precompile-utils'
version = '0.9.17'

[dependencies]
# There's a problem with --all-features when this is moved under dev-deps
evm = { git = "https://github.com/rust-blockchain/evm", rev = "b7b82c7e1fc57b7449d6dfa6826600de37cc1e65", default-features = false, optional = true }
impl-trait-for-tuples = "0.2.2"
log = { version = "0.4", default-features = false }
num_enum = { version = "0.6.1", default-features = false }
sha3 = { version = "0.10", default-features = false }
similar-asserts = { version = "1.5.0", optional = true }

precompile-utils-macro = { path = "macro" }

# Substrate
frame-support = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.42", default-features = false }
frame-system = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.42", default-features = false }
parity-scale-codec = { version = "3.0.0", default-features = false, features = ["derive"] }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.42", default-features = false }
sp-io = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.42", default-features = false }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.42", default-features = false }
sp-std = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.42", default-features = false }

# Frontier
fp-evm = { git = "https://github.com/paritytech/frontier", branch = "polkadot-v0.9.42", default-features = false }
pallet-evm = { git = "https://github.com/paritytech/frontier", branch = "polkadot-v0.9.42", default-features = false, features = ["forbid-evm-reentrancy"] }

# Polkadot / XCM
xcm = { git = "https://github.com/paritytech/polkadot", default-features = false, branch = "release-v0.9.42" }

assert_matches = "1.3.0"

[dev-dependencies]
hex-literal = "0.4.1"

[features]
default = ["std"]
std = [
    "evm/std",
    "parity-scale-codec/std",
    "fp-evm/std",
    "frame-support/std",
    "frame-system/std",
    "pallet-evm/std",
    "sp-core/std",
    "sp-io/std",
    "sp-runtime/std",
    "sp-std/std",
    "xcm/std",
]
testing = ["similar-asserts", "std"]
