[package]
name = "itp-node-api-metadata-provider"
version = "0.9.0"
authors = ['Trust Computing GmbH <info@litentry.com>', 'Integritee AG <hello@integritee.network>']
edition = "2021"

[dependencies]
# crates.io

# sgx dependencies
sgx_tstd = { workspace = true, optional = true }

# sgx enabled external libraries
thiserror_sgx = { optional = true, workspace = true }

# std compatible external libraries (make sure these versions match with the sgx-enabled ones above)
thiserror = { workspace = true, optional = true }

# local dependencies
itp-node-api-metadata = { workspace = true }
itp-stf-primitives = { workspace = true }

[features]
default = ["std"]
std = [
    "thiserror",
    "itp-stf-primitives/std",
]
sgx = [
    "sgx_tstd",
    "thiserror_sgx",
]
# used for unit testing only!
mocks = []
