[package]
name = "itp-enclave-metrics"
version = "0.9.0"
authors = ['Trust Computing GmbH <info@litentry.com>', 'Integritee AG <hello@integritee.network>']
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# sgx
sgx_tstd = { workspace = true, optional = true }

# no-std dependencies
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive", "full"] }
lc-stf-task-sender = { workspace = true, default-features = false }
substrate-fixed = { workspace = true }

[features]
default = ["std"]
std = [
    "substrate-fixed/std",
    "codec/std",
]
sgx = [
    "sgx_tstd",
]
