[package]
name = "vc-issuance"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# std dependencies
futures = { version = "0.3.8", optional = true }
thiserror = { version = "1.0.26", optional = true }
threadpool = { version = "1.8.0", optional = true }

# sgx dependencies
futures_sgx = { package = "futures", git = "https://github.com/mesalock-linux/futures-rs-sgx", optional = true }
hex-sgx = { package = "hex", git = "https://github.com/mesalock-linux/rust-hex-sgx", tag = "sgx_1.1.3", features = ["sgx_tstd"], optional = true }
sgx_tstd = { git = "https://github.com/apache/teaclave-sgx-sdk.git", branch = "master", features = ["net", "thread"], optional = true }
thiserror_sgx = { package = "thiserror", git = "https://github.com/mesalock-linux/thiserror-sgx", tag = "sgx_1.1.3", optional = true }
threadpool_sgx = { git = "https://github.com/mesalock-linux/rust-threadpool-sgx", package = "threadpool", tag = "sgx_1.1.3", optional = true }
url_sgx = { package = "url", git = "https://github.com/mesalock-linux/rust-url-sgx", tag = "sgx_1.1.3", optional = true }

# no_std dependencies
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive"] }
log = { version = "0.4", default-features = false }
sp-core = { default-features = false, features = ["full_crypto"], git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.39" }

# internal dependencies
ita-stf = { path = "../../../app-libs/stf", default-features = false }
itp-types = { path = "../../../core-primitives/types", default-features = false }

itp-enclave-metrics = { path = "../../../core-primitives/enclave-metrics", default-features = false }
itp-ocall-api = { path = "../../../core-primitives/ocall-api", default-features = false }
itp-sgx-crypto = { path = "../../../core-primitives/sgx/crypto", default-features = false }
itp-sgx-externalities = { path = "../../../core-primitives/substrate-sgx/externalities", default-features = false }
itp-stf-executor = { path = "../../../core-primitives/stf-executor", default-features = false }
itp-stf-state-handler = { path = "../../../core-primitives/stf-state-handler", default-features = false }
itp-top-pool-author = { path = "../../../core-primitives/top-pool-author", default-features = false }

# litentry
frame-support = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.39" }
ita-sgx-runtime = { path = "../../../app-libs/sgx-runtime", default-features = false }
lc-assertion-build = { path = "../assertion-build", default-features = false }
lc-credentials = { path = "../credentials", default-features = false }
lc-data-providers = { path = "../data-providers", default-features = false }
lc-identity-verification = { path = "../identity-verification", default-features = false }
lc-stf-task-receiver = { path = "../stf-task/receiver", default-features = false }
lc-stf-task-sender = { path = "../stf-task/sender", default-features = false }
litentry-primitives = { path = "../../primitives", default-features = false }

[features]
default = ["std"]
sgx = [
    "threadpool_sgx",
    "futures_sgx",
    "hex-sgx",
    "sgx_tstd",
    "thiserror_sgx",
    "url_sgx",
    "ita-stf/sgx",
    "itp-sgx-externalities/sgx",
    "itp-stf-executor/sgx",
    "itp-stf-state-handler/sgx",
    "itp-top-pool-author/sgx",
    "sp-core/full_crypto",
    "litentry-primitives/sgx",
    "lc-identity-verification/sgx",
    "lc-assertion-build/sgx",
    "lc-credentials/sgx",
    "lc-data-providers/sgx",
    "lc-stf-task-receiver/sgx",
    "lc-stf-task-sender/sgx",
]
std = [
    "threadpool",
    "futures",
    "log/std",
    "thiserror",
    "itp-types/std",
    "itp-top-pool-author/std",
    "itp-stf-executor/std",
    "itp-stf-state-handler/std",
    "sp-core/std",
    "litentry-primitives/std",
    "lc-identity-verification/std",
    "lc-assertion-build/std",
    "ita-sgx-runtime/std",
    "frame-support/std",
    "lc-credentials/std",
    "lc-data-providers/std",
    "lc-stf-task-receiver/std",
    "lc-stf-task-sender/std",
]
