[package]
name = "sgx-verify"
version = "0.1.4"
description = "a certificate verification and IAS report parser crate for the teerex pallet"
authors = ['Trust Computing GmbH <info@litentry.com>', 'Integritee AG <hello@integritee.network>']
homepage = 'https://litentry.com/'
repository = 'https://github.com/litentry/litentry-parachain'
license = "GPL-3.0"
edition = "2021"

[dependencies]
base64 = { version = "0.21", default-features = false, features = ["alloc"] }
chrono = { version = "0.4", default-features = false, features = ["serde"] }
codec = { version = "3.0.0", default-features = false, features = ["derive"], package = "parity-scale-codec" }
der = { default-features = false, version = "0.6.0" }
hex = { default-features = false, version = "0.4.3", features = ["alloc"] }
ring = { version = "0.16.20", default-features = false, features = ["alloc"] }
scale-info = { version = "2.0.1", default-features = false, features = ["derive"] }
serde = { default-features = false, version = "1.0.140", features = ["derive"] }
serde_json = { version = "1.0", default-features = false, features = ["alloc"] }
webpki = { git = "https://github.com/rustls/webpki", version = "=0.102.0-alpha.3", rev = "da923ed", package = "rustls-webpki", default-features = false, features = ["alloc", "ring"] }
x509-cert = { default-features = false, version = "0.1.0", features = ["alloc"] }

# local
teerex-primitives = { path = "../../../primitives/teerex", default-features = false }

# substrate dependencies
frame-support = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.42" }
sp-core = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.42" }
sp-std = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.42" }

[dev-dependencies]
hex-literal = "0.4.1"

[features]
default = ["std"]
std = [
    "base64/std",
    "chrono/std",
    "codec/std",
    "der/std",
    "hex/std",
    "ring/std",
    "scale-info/std",
    "serde/std",
    "serde_json/std",
    "webpki/std",
    "x509-cert/std",
    # local
    "teerex-primitives/std",
    # substrate
    "frame-support/std",
    "sp-core/std",
    "sp-std/std",
]
