[package]
authors = ["Integritee AG <hello@integritee.network>"]
edition = "2021"
name = "itp-time-utils"
version = "0.9.0"

[dependencies]
sgx_tstd = { branch = "master", git = "https://github.com/apache/teaclave-sgx-sdk.git", optional = true }

[features]
default = ["std"]
sgx = [
    "sgx_tstd",
]
std = [
]
