[package]
name = "itp-time-utils"
version = "0.9.0"
authors = ['Litentry Dev and Integritee AG <hello@integritee.network>']
edition = "2021"

[dependencies]
sgx_tstd = { branch = "master", git = "https://github.com/apache/teaclave-sgx-sdk.git", optional = true }

[features]
default = ["std"]
std = [
]
sgx = [
    "sgx_tstd",
]
