[package]
name = "precompile-utils-macro"
authors = ["StakeTechnologies", "PureStake"]
description = ""
version = "0.1.0"
edition.workspace = true
homepage.workspace = true
repository.workspace = true

[lib]
proc-macro = true

[[test]]
name = "tests"
path = "tests/tests.rs"

[dependencies]
num_enum = { version = "0.5.3", default-features = false }
proc-macro2 = { workspace = true }
quote = { workspace = true }
sha3 = { version = "0.10", default-features = false }
syn = { workspace = true, features = ["extra-traits", "fold", "full", "visit"] }
