[package]
authors = ["Trust Computing GmbH <info@litentry.com>"]
edition = '2021'
name = 'precompile-utils-macro'
version = '0.1.0'

[lib]
proc-macro = true

[[test]]
name = "tests"
path = "tests/tests.rs"

[dependencies]
num_enum = { workspace = true }
proc-macro2 = { workspace = true }
quote = { workspace = true }
sha3 = { workspace = true }
syn = { workspace = true, features = ["extra-traits", "fold", "full", "visit"] }
