[package]
name = "lc-vc-task-sender"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# std dependencies
futures = { version = "0.3.8", optional = true }
jsonrpc-core = { version = "18", optional = true }
thiserror = { version = "1.0.26", optional = true }
url = { version = "2.0.0", optional = true }

# sgx dependencies
futures_sgx = { package = "futures", git = "https://github.com/mesalock-linux/futures-rs-sgx", optional = true }
jsonrpc-core_sgx = { package = "jsonrpc-core", git = "https://github.com/scs/jsonrpc", branch = "no_std_v18", default-features = false, optional = true }
sgx_tstd = { branch = "master", git = "https://github.com/apache/teaclave-sgx-sdk.git", features = ["net", "thread"], optional = true }
thiserror_sgx = { package = "thiserror", git = "https://github.com/mesalock-linux/thiserror-sgx", tag = "sgx_1.1.3", optional = true }
url_sgx = { package = "url", git = "https://github.com/mesalock-linux/rust-url-sgx", tag = "sgx_1.1.3", optional = true }

# no_std dependencies
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive"] }
lazy_static = { version = "1.1.0", features = ["spin_no_std"] }
log = { version = "0.4", default-features = false }

# substrate dependencies
sp-runtime = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.42", default-features = false }
sp-std = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.42", default-features = false }

# internal dependencies
itp-types = { path = "../../../../core-primitives/types", default-features = false }

# litentry
itp-stf-primitives = { default-features = false, path = "../../../../core-primitives/stf-primitives" }
lc-stf-task-sender = { path = "../../stf-task/sender", default-features = false }
litentry-primitives = { path = "../../../primitives", default-features = false }

[features]
default = ["std"]
sgx = [
    "sgx_tstd",
    "thiserror_sgx",
    "url_sgx",
    "lc-stf-task-sender/sgx",
    "futures_sgx",
    "jsonrpc-core_sgx",
]
std = [
    "log/std",
    "sp-runtime/std",
    "sp-std/std",
    "thiserror",
    "url",
    "itp-types/std",
    "lc-stf-task-sender/std",
    "futures",
    "jsonrpc-core",
]
