name: Label PRs

on:
  pull_request:
    types: [opened,ready_for_review]

jobs:
  label-prs:
    runs-on: ubuntu-latest
    steps:
      - name: Label drafts
        uses: andymckay/labeler@master
        if: github.event.pull_request.draft == true
        with:
          remove-labels: 'S1-pleasereview'

      - name: Label PRs
        uses: andymckay/labeler@master
        if: github.event.pull_request.draft == false
        with:
          add-labels: 'S1-pleasereview'