name: Rust

on:
  push:
    branches: [ rococo-v1 ]
    branches: [ integration-test ]
  pull_request:
    branches: [ rococo-v1 ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Add wasm toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly-2020-10-06
        target: wasm32-unknown-unknown
        override: true
    - name: Build relay node and parachain
      run: |
        cargo build --release
        cd polkadot
        cargo build --release --features=real-overseer
        cd ..
    - name: Run unit tests
      run: cargo test --verbose
    - name: Run integration test
      run: |
        cd ts-tests
        ../polkadot/start-bob.sh.bk& ../polkadot/start-alice.sh.bk&
        npm install 
        npm test

