name: Build & Test

on:
  push:
    branches:
      - dev
    paths-ignore:
      - '**/dependabot.yml'
      - '**/README.md'
  pull_request:
    branches:
      - dev
    paths-ignore:
      - '**/dependabot.yml'
      - '**/README.md'
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-test:
    if: "!contains(github.event.commits[0].message, '[SKIP CI]')"
    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: true
    runs-on: self-hosted
    steps:
    - name: Checkout codes
      uses: actions/checkout@v2

    - name: Install toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: wasm32-unknown-unknown
        override: true

    - name: Build binary and run CI
      timeout-minutes: 50
      run: |
        make test-ci-binary

    - name: Archive logs if test fails
      uses: actions/upload-artifact@v2
      if: ${{ failure() }}
      with:
        name: ci-artifacts
        path: /tmp/parachain_dev/
        retention-days: 7

    - name: Clean up
      if: ${{ always() }}
      run: |
        make clean-local-binary
