name: Build & Test

on:
  push:
    branches:
      - dev
      - 133-improve-ci-gh-actions
    paths-ignore:
      - '**/dependabot.yml'
      - '**/README.md'
  pull_request:
    branches:
      - dev
    paths-ignore:
      - '**/dependabot.yml'
      - '**/README.md'
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-test:
    if: "!contains(github.event.commits[0].message, '[SKIP CI]')"
    runs-on: self-hosted
    steps:
    - name: Checkout codes
      uses: actions/checkout@v2

    - name: Build docker image
      uses: ./.github/workflows/build_docker_image.yml
      with:
        branch: ${GITHUB_REF#refs/heads/}

    - name: Start docker containers and run CI
      run: |
        make test-ci

    - name: Archive logs if test fails
      uses: actions/upload-artifact@v2
      if: ${{ failure() }}
      with:
        name: ci-log
        path: /tmp/parachain_ci_test.log
        retention-days: 7

    - name: Push docker image on dev branch if test passes
      if: ${{ success() && (github.ref == 'refs/heads/dev') }}
      uses: ./.github/workflows/push_docker_image.yml
      with:
        tag: latest

    - name: Clean up
      if: ${{ always() }}
      run: |
        rm -f /tmp/parachain_ci_test.log
        make clean-local-docker
