name: Rust

on:
  push:
    branches: [ rococo-v1 ]
  pull_request:
    branches: [ rococo-v1 ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-test:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Add wasm toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly-2021-03-24
        target: wasm32-unknown-unknown
        override: true
    - name: Build relay node and parachain
      run: |
        cargo build --release
        cd polkadot
        cargo build --release
        cd ..
    - name: Build token server
      run: |
        cd token-server
        cargo build --release
        cd ..
    - name: Run integration test
      run: |
        cd ts-tests
        npm install 
        npm test

