name: Rust

on:
  push:
    branches: [ rococo-v1 ]
  pull_request:
    branches: [ rococo-v1 ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Add wasm toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        target: wasm32-unknown-unknown
        override: true
    - name: Build relay node and parachain
      run: |
        cargo build --release
        cd polkadot
        cargo build --release --features=real-overseer
        cd ..
    - name: Run integration test
      run: |
        cd ts-tests
        npm install 
        ./scripts/start-alice-and-bob.sh
        npm test

