name: Build docker image

on:
  workflow_call:
    inputs:
      branch:
        default: 'dev'
        required: false
        type: string
      tag:
        default: 'latest'
        required: false
        type: string

env:
  CARGO_TERM_COLOR: always

jobs:
  build-docker-image:
    runs-on: self-hosted
    steps:
    - name: Checkout codes
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.inputs.branch }}

    - name: Build docker image
      run: |
        ./scripts/build-docker.sh ${{ github.event.inputs.tag }}
        echo "============================="
        docker images

