name: Build & Test

on:
  push:
    branches:
      - dev
    paths-ignore:
      - '**/dependabot.yml'
      - '**/README.md'
  pull_request:
    branches:
      - dev
    paths-ignore:
      - '**/dependabot.yml'
      - '**/README.md'
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-test:
    if: "!contains(github.event.commits[0].message, '[SKIP CI]')"
    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: true
    runs-on: self-hosted
    steps:
    - name: Checkout codes
      uses: actions/checkout@v2

    - name: Build docker image
      timeout-minutes: 40
      run: |
        ./scripts/build-docker.sh
        echo "============================="
        docker images

    - name: Start docker containers and run CI
      timeout-minutes: 30
      run: |
        make test-ci-binary

    - name: Archive logs if test fails
      uses: actions/upload-artifact@v2
      if: ${{ failure() }}
      with:
        name: ci-artifacts
        path: /tmp/parachain_dev/
        retention-days: 7

    - name: Push docker image on dev branch if test passes
      if: ${{ success() && (github.event_name == 'push') && (github.ref == 'refs/heads/dev') }}
      run:
        docker push litentry/litentry-parachain:latest

    - name: Clean up
      if: ${{ always() }}
      run: |
        make clean-local-binary
