name: Build & Test

on:
  push:
    branches:
      - dev
    paths-ignore:
      - '**/dependabot.yml'
      - '**/README.md'
  pull_request:
    branches:
      - dev
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  check-file-change:
    runs-on: ubuntu-latest
    outputs:
      ts: ${{ steps.filter.outputs.ts }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Checks to see if any files in the PR/commit match one of the listed file types.
      # We can use this filter to decide whether or not to build docker images
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            ts:
              - 'ts-tests/**'

  check-cargo-fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          components: rustfmt
          target: wasm32-unknown-unknown
          default: true

      - name: Run cargo fmt check
        run: make fmtcheck

  check-cargo-clippy:
    runs-on: ubuntu-latest
    needs: check-cargo-fmt
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          components: clippy
          target: wasm32-unknown-unknown
          default: true

      - name: Run cargo clippy check
        run: make clippy

  build-docker:
    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: true
    # run the docker build on our self-hosted runner, which takes < 20min
    # on a standard github runner it takes ~1 hour
    # runs-on: self-hosted
    runs-on: ubuntu-latest
    needs: [check-cargo-fmt, check-file-change]
    steps:
      - name: Checkout codes
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup docker buildx
        uses: docker/setup-buildx-action@v1

      # - name: Build docker image
      #   timeout-minutes: 80
      #   run: |
      #     ./scripts/build-docker.sh
      #     echo "============================="
      #     docker images

      - name: Build docker image
        if: needs.check-file-change.outputs.ts == 'false'
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: litentry/litentry-parachain:latest
          outputs: type=docker,dest=litentry-parachain.tar
          push: false
          file: docker/Dockerfile
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Save docker image
        # if the changed files are ts-tests/** files,
        # do not build the docker image, just pull it instead
        if: needs.check-file-change.outputs.ts == 'true'
        run: |
          docker pull litentry/litentry-parachain:latest
          docker save litentry/litentry-parachain:latest -o litentry-parachain.tar

      # - name: Save docker image
      #   run: |
      #     docker save litentry/litentry-parachain:latest -o litentry-parachain.tar

      - name: Upload docker image
        uses: actions/upload-artifact@v3
        with:
          name: docker-artifact
          path: litentry-parachain.tar

  run-ts-tests:
    runs-on: ubuntu-latest
    needs: build-docker
    strategy:
      matrix:
        chain:
          - litmus
          - litentry
    steps:
      - name: Checkout codes
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/download-artifact@v3
        with:
          name: docker-artifact

      - name: Load docker image
        run: |
          docker load -i litentry-parachain.tar

      - name: Run ts tests for ${{ matrix.chain }}
        timeout-minutes: 20
        run: |
          make test-ts-docker-${{ matrix.chain }}

      - name: Archive logs if test fails
        uses: actions/upload-artifact@v3
        if: ${{ failure() }}
        with:
          name: ${{ matrix.chain }}-ts-tests-artifacts
          path: /tmp/parachain_dev/
          retention-days: 3

      - name: Clean up for ${{ matrix.chain }}
        if: ${{ always() }}
        run: |
          make clean-docker-${{ matrix.chain }}

  run-cargo-unit-tests:
    runs-on: ubuntu-latest
    needs: [check-cargo-fmt, check-file-change]
    if: needs.check-file-change.outputs.ts == 'false'
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          target: wasm32-unknown-unknown
          default: true

      - name: Run unittests
        run: cargo test --release -p pallet-* --lib

  run-cargo-runtime-tests:
    runs-on: ubuntu-latest
    needs: [check-cargo-fmt, check-file-change]
    if: needs.check-file-change.outputs.ts == 'false'
    env:
      RUST_BACKTRACE: full
      RUSTC_WRAPPER: sccache
      SCCACHE_CACHE_SIZE: 10G
      SCCACHE_DIR: /home/runner/.cache/sccache
      CARGO_INCREMENTAL: 0
    strategy:
      matrix:
        chain:
          - litmus
          - litentry
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          target: wasm32-unknown-unknown
          default: true

      # use sccache to accelerate binary compilation
      # see https://www.infinyon.com/blog/2021/04/github-actions-best-practices/
      - name: Install sccache
        env:
          LINK: https://github.com/mozilla/sccache/releases/download
          SCCACHE_VERSION: v0.2.15
        run: |
          SCCACHE_FILE=sccache-$SCCACHE_VERSION-x86_64-unknown-linux-musl
          mkdir -p $HOME/.local/bin
          curl -L "$LINK/$SCCACHE_VERSION/$SCCACHE_FILE.tar.gz" | tar xz
          mv -f $SCCACHE_FILE/sccache $HOME/.local/bin/sccache
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Cache cargo registry
        uses: actions/cache@v2
        continue-on-error: false
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            cargo-

      - name: Cache sccache
        uses: actions/cache@v2
        continue-on-error: false
        with:
          path: /home/runner/.cache/sccache
          key: sccache-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            sccache-

      - name: Run runtime integration tests
        run: cargo test --release -p ${{ matrix.chain }}-parachain-runtime --lib

      - name: Print sccache stats
        run: sccache --show-stats

  push-docker-image:
    runs-on: ubuntu-latest
    needs: ["check-cargo-clippy", "run-cargo-unit-tests", "run-cargo-runtime-tests", "run-ts-tests"]
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: docker-artifact

      - name: Load docker image
        run: |
          docker load -i litentry-parachain.tar

      - name: Dockerhub login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Push docker image on dev branch if test passes
        if: ${{ success() && (github.event_name == 'push') && (github.ref == 'refs/heads/dev') }}
        run:
          docker push litentry/litentry-parachain:latest
