name: Tests Coverage

on:
  push:
    branches:
      - dev
    paths-ignore:
      - "**/dependabot.yml"
      - "**/README.md"
  pull_request:
    branches:
      - dev
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Coverage Report
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          components: rustfmt
          target: wasm32-unknown-unknown
          default: true

      - name: Install additional dependencies
        run: |
            sudo apt update -y &&
            sudo apt install -y cmake pkg-config libssl-dev git gcc build-essential git clang libclang-dev protobuf-compiler

      - name: Install cargo-tarpaulin
        run: |
            cargo install cargo-tarpaulin

      - name: Run cargo-tarpaulin
        run: |
          PACKAGES=$(find pallets/ -name "Cargo.toml" | while read -r f; do pn=$(grep name "$f" | \
                     tr '"' "'" | sed "s/'$//;s/.*'//"); f="file://$(pwd)/${f//\/Cargo.toml/#$pn}"; \
                     cargo pkgid "$f"; done | paste -s -d "," -)
          cargo tarpaulin --no-fail-fast -o Xml -p "$PACKAGES" \
          --exclude-files **/mock.rs **/weights.rs **/benchmarking.rs **/weights/* node/* runtime/*

      - name: Upload to codecov.io
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: false
          verbose: true

