name: Tests Coverage

on:
  push:
    branches:
      - coverage_test
    paths-ignore:
      - "**/dependabot.yml"
      - "**/README.md"
  pull_request:
    branches:
      - dev
  workflow_dispatch:

env:
  TARPAULIN_VERSION: 0.20.1
  # LIBCLANG_PATH: "/usr/lib/llvm-11/lib" # default `llvm-config --prefix`
  # SCCACHE_CACHE_SIZE: "100G"
  CARGO_INCREMENTAL: 0

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Coverage Report
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          components: rustfmt
          target: wasm32-unknown-unknown
          default: true

      - name: Install additional dependencies
        run: |
            sudo apt update -y &&
            sudo apt install -y cmake pkg-config libssl-dev git gcc build-essential git clang libclang-dev

      - name: Install cargo-tarpaulin
        run: |
            cargo install cargo-tarpaulin
          # wget https://github.com/xd009642/tarpaulin/releases/download/${{ env.TARPAULIN_VERSION }}/cargo-tarpaulin-${{ env.TARPAULIN_VERSION }}-travis.tar.gz
          # tar -zxvf cargo-tarpaulin-${{ env.TARPAULIN_VERSION }}-travis.tar.gz -C $HOME/.cargo/bin

      - name: Run cargo-tarpaulin
        run: |
          # cargo tarpaulin --release --no-fail-fast --workspace -e node primitives runtime scritps templates ts-tests
          PACKAGES=$(find pallets/ -name "Cargo.toml" | xargs grep name | tr '"' "'" | sed "s/'$//;s/.*'//" | paste -s -d "," -)
          cargo tarpaulin --no-fail-fast -o Xml -p "$PACKAGES"

      - name: Upload to codecov.io
        uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false)

