name: Create release draft

on:
  workflow_dispatch:
    inputs:
      release_type:
        type: choice
        description: Which release type
        options:
          - client
          - runtime
          - both
      release_tag:
        description: an existing tag for creating release (e.g. v1.2.3)
        required: true
      diff_tag:
        description: an existing tag to run diff against (e.g. v1.2.0)
        default: ''
        required: false
      genesis_release:
        type: choice
        description: If any of the genesis artefacts should be released alongside
        options:
          - none
          - litmus
          - rococo
          - litentry

env:
  RELEASE_TYPE: ${{ github.event.inputs.release_type }}
  RELEASE_TAG: ${{ github.event.inputs.release_tag }}
  DIFF_TAG: ${{ github.event.inputs.diff_tag }}
  GENESIS_RELEASE: ${{ github.event.inputs.genesis_release }}

jobs:
  ## build runtime wasm ##
  build-wasm:
    if: github.event.inputs.release_type != 'client'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        chain:
          - litmus
          # TODO - rococo
          - litentry
    steps:
      - name: Checkout codes on ${{ env.RELEASE_TAG }}
        uses: actions/checkout@v2
        with:
          ref: ${{ env.RELEASE_TAG }}
          fetch-depth: 0

      - name: Build with srtool
        id: srtool_build
        uses: chevdor/srtool-actions@v0.3.0
        with:
          chain: ${{ matrix.chain }}-parachain
          runtime_dir: runtime/${{ matrix.chain }}

      - name: Summary
        run: |
          echo '${{ steps.srtool_build.outputs.json }}' | jq . > ${{ matrix.chain }}-parachain-srtool-digest.json
          echo "==============================================="
          cat ${{ matrix.chain }}-parachain-srtool-digest.json
          cp ${{ steps.srtool_build.outputs.wasm_compressed }} ${{ matrix.chain }}-parachain-runtime.compact.compressed.wasm

      - name: Upload wasm artefacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.chain }}-parachain-runtime
          path: |
            ${{ matrix.chain }}-parachain-srtool-digest.json
            ${{ matrix.chain }}-parachain-runtime.compact.compressed.wasm

  ## build docker image of client binary ##
  build-docker:
    if: github.event.inputs.release_type != 'runtime'
    runs-on: self-hosted
    steps:
      - name: Checkout codes on ${{ env.RELEASE_TAG }}
        uses: actions/checkout@v2
        with:
          ref: ${{ env.RELEASE_TAG }}
          fetch-depth: 0

      - name: Build docker image
        run: |
          ./scripts/build-docker.sh prod ${{ env.RELEASE_TAG }}
          echo "============================="
          docker images

      - name: Push docker image
        run: |
          docker push litentry/litentry-parachain:${{ env.RELEASE_TAG }}

      - name: Remove dangling images if any
        run: |
          [ -z "$(docker images --filter=dangling=true -q)" ] || docker rmi -f $(docker images --filter=dangling=true -q)

      - name: Generate genesis artefacts if need
        if: github.event.inputs.genesis_release != 'none'
        run: |
          docker run --rm litentry/litentry-parachain:${{ env.RELEASE_TAG }} export-genesis-state --chain=${{ env.GENESIS_RELEASE }} > ${{ env.GENESIS_RELEASE }}-genesis-state
          docker run --rm litentry/litentry-parachain:${{ env.RELEASE_TAG }} export-genesis-wasm --chain=${{ env.GENESIS_RELEASE }} > ${{ env.GENESIS_RELEASE }}-genesis-wasm

      - name: Copy client binary to disk
        run: |
          docker cp $(docker create --rm litentry/litentry-parachain:${{ env.RELEASE_TAG }}):/usr/local/bin/litentry-collator .

      - name: Upload the client binary
        uses: actions/upload-artifact@v3
        with:
          name: litentry-collator
          if-no-files-found: ignore
          path: |
            litentry-collator
            ${{ env.GENESIS_RELEASE }}-genesis-state
            ${{ env.GENESIS_RELEASE }}-genesis-wasm

  ## create the release draft ##
  create-release-draft:
    runs-on: ubuntu-latest
    # see https://github.com/actions/runner/issues/491
    # seems to be the only way to achieve this
    needs:
      - build-wasm
      - build-docker
    if: |
      !failure() && !cancelled() &&
      (success('build-wasm') || success('build-docker'))
    steps:
      - name: Checkout codes on ${{ env.RELEASE_TAG }}
        uses: actions/checkout@v2
        with:
          ref: ${{ env.RELEASE_TAG }}
          fetch-depth: 0

      - name: Download all artefacts
        uses: actions/download-artifact@v3

      - name: Generate release notes
        run: |
          ./scripts/generate-release-notes.sh ${{ github.workspace }}/.github/release_notes.md ${{ env.RELEASE_TYPE }} ${{ env.DIFF_TAG }}

      - name: Create release draft
        id: create-release-draft
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.RELEASE_TAG }}
          name: Litentry-parachain ${{ env.RELEASE_TAG }}
          body_path: ${{ github.workspace }}/.github/release_notes.md
          draft: true
          files: |
            *-parachain-runtime/*-parachain-srtool-digest.json
            *-parachain-runtime/*-parachain-runtime.compact.compressed.wasm
            litentry-collator/*
