name: Create release draft

on:
  workflow_dispatch:
    inputs:
      ref:
        description: an existing tag (e.g. v1.2.3)
        required: true
  push:
    branches:
      - 146-skeletons-for-releases


env:
  RELEASE_TAG: ${{ github.event.inputs.ref || github.ref }}

jobs:
  ## build runtime wasm ##
  build-wasm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codes on ${RELEASE_TAG}
        uses: actions/checkout@v2
        with:
          ref: ${RELEASE_TAG}

      - name: Build with srtool
        id: srtool_build
        uses: chevdor/srtool-actions@v0.3.0
        with:
          chain: litentry-parachain
          runtime_dir: runtime

      - name: Summary
        run: |
          echo '${{ steps.srtool_build.outputs.json }}' | jq . > litentry-parachain-srtool-digest.json
          echo "==============================================="
          cat litentry-parachain-srtool-digest.json
          cp ${{ steps.srtool_build.outputs.wasm }} litentry-parachain-runtime.compact.wasm
          cp ${{ steps.srtool_build.outputs.wasm_compressed }} litentry-parachain-runtime.compact.compressed.wasm

      - name: Upload wasm artefacts
        uses: actions/upload-artifact@v2
        with:
          name: litentry-parachain-runtime
          path: |
            litentry-parachain-srtool-digest.json
            litentry-parachain-runtime.compact.wasm
            litentry-parachain-runtime.compact.compressed.wasm

  ## build docker image of client binary ##
  build-docker:
    runs-on: self-hosted
    steps:
      - name: Checkout codes on ${RELEASE_TAG}
        uses: actions/checkout@v2
        with:
          ref: ${RELEASE_TAG}

      - name: Build docker image
        run: |
          ./scripts/build-docker.sh ${RELEASE_TAG}
          echo "============================="
          docker images

      - name: Copy client binary to disk
        run: |
          docker cp $(docker create --rm litentry/litentry-parachain:${RELEASE_TAG}):/usr/local/bin/litentry-collator .

      - name: Upload the client binary
        uses: actions/upload-artifact@v2
        with:
          name: litentry-collator
          path: |
            litentry-collator

  ## create the release draft ##
  create-release-draft:
    runs-on: ubuntu-latest
    needs: ["build-wasm", "build-docker"]
    steps:
      - name: Checkout codes on ${RELEASE_TAG}
        uses: actions/checkout@v2
        with:
          ref: ${RELEASE_TAG}

      - name: Download all artefacts
        uses: actions/download-artifact@v2

      - name: Generate release notes
        run: |
          echo "${GITHUB_WORKSPACE}" > ${{ github.workspace }}/.github/release_text.md

      - name: Create release draft
        id: create-release-draft
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${RELEASE_TAG}
          release_name: Litentry-parachain release ${RELEASE_TAG}
          body_path: ${{ github.workspace }}/.github/release_text.md
          draft: true
          files: |
            litentry-parachain-srtool-digest.json
            litentry-parachain-runtime.compact.wasm
            litentry-parachain-runtime.compact.compressed.wasm
            litentry-collator
