name: Deploy to Server

on:
  push:
    branches:
      - dev
    paths-ignore:
      - "**/dependabot.yml"
      - "**/README.md"
  pull_request:
    branches:
      - dev
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

jobs:
  deploy-tee-dev:
    runs-on: ubuntu-latest

    env:
      SSH_USER: ubuntu
      SSH_SERVER: 162.19.84.27

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    # - name: Install dependencies
    #   run: |
    #     sudo apt-get update
    #     sudo apt-get install -yq openssl clang libclang-dev cmake protobuf-compiler

    # local build cost 38min
    # - name: Build litentry-collator
    #   run: make build-node

    # use remote build docker 

    - name: SSH into server and restart
      run: |
        echo "${{ secrets.TEE_STAGING_SSH_PRIVATE_KEY }}" > ssh_key.pem
        chmod 600 ssh_key.pem
        ssh -i ssh_key.pem $SSH_USER@$SSH_SERVER "bash -s  ~/dev_deploy.sh restart -b -v litentry/litentry-parachain:latest litentry/litentry-worker:latest --config /opt/worker_configs/config.json --discard "
