name: Dev Integritee restart
on:
  workflow_dispatch:
    inputs:
      action:
        type: choice
        description: Select the action
        options:
        - stop
        - restart
        - restart-worker-only
jobs:
  action:
    runs-on: tee-staging
    steps:
      - name: stoping the service
        if: "${{ github.event.inputs.action == 'stop' }}"
        run: |
          sudo systemctl stop integritee.service
          cd /home/ubuntu/repo/litentry-parachain/tee-worker
          ./scripts/litentry/stop_parachain.sh
          sleep 5

      - name: restarting the service
        if: "${{ github.event.inputs.action == 'restart' }}"
        run: |
          sudo systemctl stop integritee.service
          cd /home/ubuntu/repo/litentry-parachain/tee-worker
          ./scripts/litentry/stop_parachain.sh
          sleep 60  #after stoping the docker, it takes some time to release port 9944 by docker-proxy.
          ./scripts/litentry/start_parachain.sh
          sudo systemctl start integritee.service

      - name: restarting the worker only
        if: "${{ github.event.inputs.action == 'restart-worker-only' }}"
        run: |
          sudo systemctl stop integritee.service || true
          sleep 5
          sudo systemctl start integritee.service