name: Release - Extrinsic Ordering Check

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Create release draft"]
    branches:
      - dev
    types:
      - completed

jobs:
  check:
    name: Run check
    runs-on: ubuntu-latest
    env:
      CHAIN: ${{github.event.inputs.chain}}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Pull polkadot-js-tools image
        run: docker pull jacogr/polkadot-js-tools

      - name: Prepare output and compare the metadata
        run: |
          BASE_URL=wss://parachain-eu-0.staging.litentry.io
          chains=("litmus" "litentry")
          for c in $chains; do
            REF_URL=wss://rpc.$c-parachain.litentry.io
            echo "Metadata comparison:" > output-$c.txt
            echo "Date: $(date)" >> output-$c.txt
            echo "Base: $BASE_URL" >> output-$c.txt
            echo "Reference: $REF_URL" >> output-$c.txt
            echo "Target version: $VERSION" >> output-$c.txt
            echo "Chain: $c" >> output-$c.txt
            echo "----------------------------------------------------------------------" >> output-$c.txt
            CMD="docker run --pull always --network host jacogr/polkadot-js-tools metadata $REF_URL $BASE_URL"
            echo -e "Running:\n$CMD"
            $CMD >> output-$c.txt
            sed -z -i 's/\n\n/\n/g' output-$c.txt
            cat output-$c.txt | egrep -n -i ''
            SUMMARY=$(./scripts/extrinsic-ordering-filter.sh output-$c.txt)
            echo -e $SUMMARY
            echo -e $SUMMARY >> output-$c.txt
          done

      - name: Show result
        run: |
          cat output-litmus.txt
          echo "--------------------------------------------------------------------------------"
          cat output-litentry.txt

      - name: Save output as artifact
        uses: actions/upload-artifact@v3
        with:
          name: output
          path: |
            output-litmus.txt
            output-litentry.txt
