name: Release - Extrinsic Ordering Check

on:
  workflow_run:
    workflows:
      - Create release draft
      - Issue stale bot
    branches:
      - 577-automation-extrinsic-pallet-order-check
    types:
      - requested
      - completed
  # push:
  #   branches:
  #     - 577-automation-extrinsic-pallet-order-check
  workflow_dispatch:
    inputs:
      chain:
        description: The name of the chain to compare with, should be litentry or litmus
        default: litentry
        required: true
jobs:
  check:
    name: Run check
    runs-on: ubuntu-latest
    env:
      CHAIN: ${{github.event.inputs.chain}}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Pull polkadot-js-tools image
        run: docker pull jacogr/polkadot-js-tools

      - name: Prepare output and compare the metadata
        run: |
          CHAIN=${CHAIN:-litmus}
          BASE_URL=wss://parachain-eu-0.staging.litentry.io
          LITENTRY_REF_URL=wss://rpc.litentry-parachain.litentry.io
          LITMUS_REF_URL=wss://rpc.litmus-parachain.litentry.io
          REF_URL=$LITENTRY_REF_URL
          if [ "$CHAIN" == "litmus" ]; then REF_URL=$LITMUS_REF_URL; fi
          echo "Metadata comparison:" > output.txt
          echo "Date: $(date)" >> output.txt
          echo "Base: $BASE_URL" >> output.txt
          echo "Reference: $REF_URL" >> output.txt
          echo "Target version: $VERSION" >> output.txt
          echo "Chain: $CHAIN" >> output.txt
          echo "----------------------------------------------------------------------" >> output.txt
          CMD="docker run --pull always --network host jacogr/polkadot-js-tools metadata $REF_URL $BASE_URL"
          echo -e "Running:\n$CMD"
          $CMD >> output.txt
          sed -z -i 's/\n\n/\n/g' output.txt
          cat output.txt | egrep -n -i ''
          SUMMARY=$(./scripts/extrinsic-ordering-filter.sh output.txt)
          echo -e $SUMMARY
          echo -e $SUMMARY >> output.txt

      - name: Show result
        run: |
          cat output.txt

      - name: Save output as artifact
        uses: actions/upload-artifact@v3
        with:
          name: output-${{ env.CHAIN }}
          path: |
            output.txt
