# This workflow performs the Extrinsic Ordering Check on demand using a binary

name: Release - Extrinsic Ordering Check
on:
  workflow_dispatch:
    inputs:
      # reference_url:
      #   description: The WebSocket url of the reference node
      #   default:
      #   required: false
      # reference_url:
      #   default:
      #   required: false
      # binary_url:
      #   description: A url to a Linux binary for the node containing the runtime to test
      #   default: https://releases.parity.io/polkadot/x86_64-debian:stretch/v0.9.10/polkadot
      #   required: true
      chain:
        description: The name of the chain to compare with, should be litentry or litmus
        default: litentry
        required: true

jobs:
  check:
    name: Run check
    runs-on: ubuntu-latest
    env:
      CHAIN: ${{github.event.inputs.chain}}
      BIN_URL: ${{github.event.inputs.binary_url}}
      # REF_URL: ${{github.event.inputs.reference_url}}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      # - name: Fetch binary
      #   run: |
      #     echo Fetching $BIN_URL
      #     wget $BIN_URL -O polkadot
      #     chmod a+x polkadot
      #     ./polkadot --version

      # - name: Start local node
      #   run: |
      #     echo Running on $CHAIN
      #     ./polkadot --chain=$CHAIN &

      - name: Prepare output
        run: |
          BASE_URL=wss://parachain-eu-0.staging.litentry.io
          LITENTRY_REF_URL=wss://rpc.litentry-parachain.litentry.io
          LITMUS_REF_URL=wss://rpc.litmus-parachain.litentry.io
          REF_URL=$LITENTRY_REF_URL
          if [ "$CHAIN" == "litmus" ]; then REF_URL=$LITMUS_REF_URL; fi
          echo "Metadata comparison:" > output.txt
          echo "Date: $(date)" >> output.txt
          echo "Base: $BASE_URL" >> output.txt
          echo "Reference: $REF_URL" >> output.txt
          echo "Target version: $VERSION" >> output.txt
          echo "Chain: $CHAIN" >> output.txt
          echo "----------------------------------------------------------------------" >> output.txt

      - name: Pull polkadot-js-tools image
        run: docker pull jacogr/polkadot-js-tools

      - name: Compare the metadata
        run: |
          CMD="docker run --pull always --network host jacogr/polkadot-js-tools metadata $REF_URL ws://localhost:9944"
          echo -e "Running:\n$CMD"
          $CMD >> output.txt
          sed -z -i 's/\n\n/\n/g' output.txt
          cat output.txt | egrep -n -i ''
          SUMMARY=$(./scripts/extrinsic-ordering-filter.sh output.txt)
          echo -e $SUMMARY
          echo -e $SUMMARY >> output.txt

      - name: Show result
        run: |
          cat output.txt

      # - name: Stop our local node
      #   run: pkill polkadot

      - name: Save output as artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.CHAIN }}
          path: |
            output.txt
