name: Push docker image

on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string

jobs:
  push-docker-image:
    runs-on: self-hosted
    steps:
    - name: Push docker image
      run: |
        IMAGE=litentry/litentry-parachain:${{ github.event.inputs.tag }}
        if docker image inspect "$IMAGE" >/dev/null 2>&1; then
          echo "pushing $IMAGE"
          docker push "$IMAGE"
        else
          echo "$IMAGE doesn't exist"
        fi
        

