name: Cleanup caches after PR closed
on:
  pull_request:
    types:
      - closed

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Cleanup
        run: |
          gh extension install actions/gh-actions-cache

          REPO=${{ github.repository }}
          BRANCH=${{ github.head_ref }}

          cacheKeysForPR=$(gh actions-cache list -R $REPO | cut -f 1 | grep "$BRANCH")

          ## Setting this to not fail the workflow while deleting cache keys.
          set +e
          echo "Deleting caches after PR closed for branch=$BRANCH ..."
          for cacheKey in $cacheKeysForPR
          do
            echo "  Delete cache: $cacheKey"
            gh actions-cache delete $cacheKey -R $REPO --confirm
          done
          echo "Done"
        env:
          GH_TOKEN: ${{ github.token }}
