name: Runtime upgrade

on:
  workflow_dispatch:
    inputs:
      release_tag:
        type: string
        description: release_tag
        required: ${{ github.event.release.tag_name }}
        default: ${{ github.event.release.tag_name }}
      chain:
        type: choice
        description: The chain whose runtime upgrade
        options:
          - litentry
          - rococo

env:
  DOCKER_BUILDKIT: 1


jobs:
  fork-parachain-and-launch:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        chain:
          - litentry
          - rococo
    steps:
      - name: fork-parachain-and-launch
        run:
          ./scripts/fork-parachain-and-launch.sh ${{ github.event.inputs.chain }}

      - name: download-new-runtime.wasm && runtime upgrade
        timeout-minutes: 10
        run:
          ./scripts/runtime-upgrade.sh ${{ github.event.inputs.chain }} ${{ github.event.release.tag_name }}

