name: Runtime upgrade simulation

on:
  push:
    branches:
      - dev
    paths-ignore:
      - "**/dependabot.yml"
      - "**/README.md"
  pull_request:
    branches:
      - dev
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
  workflow_dispatch:

env:
  RELEASE_TAG: ${{ github.event.inputs.release_tag }}
  DIFF_TAG: ${{ github.event.inputs.diff_tag }}
  GENESIS_RELEASE: ${{ github.event.inputs.genesis_release }}
  DOCKER_BUILDKIT: 1


job:
  fork-parachain-and-launch:
    run-on: ubuntu-latest
    strategy:
      matrix:
        chain:
          - litmus
          - litentry
          - rococo
    steps:
      - name: fork-parachain
        run:
          make fork-parachain-${{ matrix.chain }}
      - name: download-new-runtime.wasm && runtime upgrade
        run:
          RELEASE_TAG=${{ env.RELEASE_TAG }}
#          or same above add the command in makefile
          ./scripts/runtime-upgrade.sh ${{ matrix.chain }} RELEASE_TAG
#          make runtime-upgrade-${{ matrix.chain }}





