name: Runtime upgrade simulation

on:
  push:
    branches:
      - 378-GA-for-runtime-upgrade-simulation
    paths-ignore:
      - "**/dependabot.yml"
      - "**/README.md"
  pull_request:
    branches:
      - 378-GA-for-runtime-upgrade-simulation
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
  workflow_dispatch:
    inputs:
      ReLEASE_TAG:
        type: string
        # if the runtime-benchmarks image should be rebuilt or pulled from hub
        description: rebuild-docker
        required: ${{ github.event.release.tag_name }}
        default: ${{ github.event.release.tag_name }}
      litentry:
        type: boolean
        description: litentry
        required: true
        default: false
      rococo:
        type: boolean
        description: rococo
        required: true
        default: false


env:
#  RELEASE_TAG: ${{ github.event.release.tag_name }}
  DIFF_TAG: ${{ github.event.release.diff_tag }}
  GENESIS_RELEASE: ${{ github.event.inputs.genesis_release }}
  DOCKER_BUILDKIT: 1


job:
  fork-parachain-and-launch:
    run-on: ubuntu-latest
    strategy:
      matrix:
        chain:
          - litentry
          - rococo
    steps:
      - name: fork-parachain
        run:
          ./scripts/fork-parachain-and-launch.sh ${{matrix.chain}}

      - name: download-new-runtime.wasm && runtime upgrade
        timeout-minutes: 10
        run:
          RELEASE_TAG=${{ env.RELEASE_TAG }}
          ./scripts/runtime-upgrade.sh ${{ matrix.chain }} $RELEASE_TAG






