name: Runtime upgrade

on:
  release:
    types: [released]

  workflow_dispatch:
    inputs:
      release_tag:
        description: runtime.wasm release_tag
        default: "v0.9.13"
        required: true
      chain:
        type: choice
        default: rococo
        description: The chain whose runtime upgrade
        options:
          - litentry
          - rococo

jobs:
  fork-parachain-and-launch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codes on ${{ github.ref }}
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: fork-parachain-and-launch
        run: |
          ./scripts/fork-parachain-and-launch.sh ${{ github.event.inputs.chain }}

      - name: download-new-runtime.wasm && runtime upgrade
        timeout-minutes: 10
        run: |
          ./scripts/runtime-upgrade.sh ${{ github.event.inputs.chain }} ${{ github.event.inputs.release_tag }}
