name: Staging Integritee restart
on:
  workflow_dispatch:
    inputs:
      action:
        type: choice
        description: Select the action
        options: 
        - stop
        - restart
jobs:
  action:
    runs-on: tee-staging
    steps:
      - name: stoping the service
        if: "${{ github.event.inputs.action == 'stop' }}"
        run: |
          sudo systemctl stop integritee.service
      - name: restarting the service
        if: "${{ github.event.inputs.action == 'restart' }}"
        run: |
          sudo systemctl stop integritee.service || true
          sleep 5
          sudo systemctl start integritee.service