name: Staging SGX parachain

on:
  workflow_dispatch:
    inputs:
      action:
        type: choice
        description: Select the action
        required: true
        default: stop
        options: 
        - stop
        - start

jobs:
  action:
    runs-on: self-hosted #tee-staging (162.19.84.27)

    steps:
      - name: restarting the service
        if: "${{ github.event.inputs.action == 'stop' }}"
        run: |
          sudo systemctl stop integritee.service

      - name: stoping the service
        if: "${{ github.event.inputs.action == 'start' }}"
        run: |
          sudo systemctl start integritee.service