name: Tee-worker CI

# this is a modified version of tee-worker/.github/workflows/build_and_test.yml with
# extra triggering control.
#
# the original file (`tee-worker/.github/workflows/build_and_test.yml`) is kept to sync
# upstream changes, therefore we need to manually apply the changes to this file.

# tried symbolic link -- didn't work, see https://stackoverflow.com/a/71704019

on:
  workflow_dispatch:
  push:
    branches:
      - tee-dev
  pull_request:
    branches:
      - tee-dev

env:
  CARGO_TERM_COLOR: always
  LOG_DIR: logs
  BUILD_CONTAINER_NAME: integritee_worker_enclave_test
  UPLOAD_DOWNLOAD_DIR_PREFIX: /tmp

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# to minimise the changes by setting a default working directory
# please note it only applies to the `run` command, not `use` command
# defaults:
#   run:
#     working-directory: tee-worker

jobs:
  build-parachain-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build docker image
        run: |
          docker pull litentry/litentry-parachain:tee-dev

      - name: Save docker image
        run: |
          docker save litentry/litentry-parachain:tee-dev -o ${{ env.UPLOAD_DOWNLOAD_DIR_PREFIX }}/litentry-parachain.tar

      - name: Upload docker image
        uses: actions/upload-artifact@v3
        with:
          name: parachain-artifact
          path: ${{ env.UPLOAD_DOWNLOAD_DIR_PREFIX }}/litentry-parachain.tar

  # Only push docker image when tests are passed and it's a push event
  push-docker-image:
    runs-on: ubuntu-latest
    needs:
      - build-parachain-docker
    if: ${{ success() }}
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: parachain-artifact
          path: ${{ env.UPLOAD_DOWNLOAD_DIR_PREFIX }}

      - name: Load docker image
        run: |
          ls -l ${{ env.UPLOAD_DOWNLOAD_DIR_PREFIX }}
          ls -l ${{ env.UPLOAD_DOWNLOAD_DIR_PREFIX }}/litentry-parachain.tar
          docker load -i ${{ env.UPLOAD_DOWNLOAD_DIR_PREFIX }}/litentry-parachain.tar

      - name: Dockerhub login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Push docker image
        run: docker push litentry/litentry-parachain:tee-dev
