services:
  demo-direct-call:
    image: litentry-cli:dev
    devices:
      - "${SGX_PROVISION:-/dev/null}:/dev/sgx/provision"
      - "${SGX_ENCLAVE:-/dev/null}:/dev/sgx/enclave"
    volumes:
      - "${AESMD:-/dev/null}:/var/run/aesmd"
    build:
      context: ${PWD}/..
      dockerfile: build.Dockerfile
      target: deployed-client
    depends_on:
      litentry-node:
        condition: service_healthy
      litentry-worker-1:
        condition: service_healthy
      litentry-worker-2:
        condition: service_healthy
    networks:
      - litentry-test-network
    entrypoint:
      "/usr/local/worker-cli/demo_direct_call_2_workers.sh -p 9912 -u ws://litentry-node
      -V wss://litentry-worker-1 -A 2011 -W wss://litentry-worker-2 -B 2012 -C /usr/local/bin/litentry-cli 2>&1"
    restart: "no"
networks:
  litentry-test-network:
    driver: bridge