services:
  # this is actually litentry parachain, keep the integritee name so that we don't have change
  # the service name everywhere in other yml files
  integritee-node:
    image: litentry/litentry-parachain:tee-dev
    container_name: integritee-node
    networks:
      - integritee-test-network
    command: --dev --unsafe-ws-external --unsafe-rpc-external --ws-port=9912
  integritee-worker-1:
    image: integritee-worker:dev
    container_name: integritee-worker-1
    build:
      context: ..
      dockerfile: build.Dockerfile
      target: deployed-worker
    depends_on: ['integritee-node']
    environment:
      - RUST_LOG=warn,ws=warn,sp_io=warn,substrate_api_client=warn,jsonrpsee_ws_client=warn,jsonrpsee_ws_server=warn,enclave_runtime=warn,integritee_service=warn,ita_stf=warn,enclave_runtime::top_pool_execution=info
    networks:
      - integritee-test-network
    # sleep 20 to give the node a bit time to be fully ready, otherwise the enclave
    # registration extrinsic is sent too early for the node to handle
    entrypoint: "dockerize -wait tcp://integritee-node:9912 -timeout 30s
      sleep 20 && /usr/local/bin/integritee-service --clean-reset --ws-external -M integritee-worker-1 -T wss://integritee-worker-1
      -u ws://integritee-node -U ws://integritee-worker-1 -P 2011 -w 2101 -p 9912 -h 4645
      run --dev --skip-ra"
    restart: "no"
  integritee-worker-2:
    image: integritee-worker:dev
    container_name: integritee-worker-2
    build:
      context: ..
      dockerfile: build.Dockerfile
      target: deployed-worker
    depends_on: ['integritee-node', 'integritee-worker-1']
    environment:
      - RUST_LOG=warn,ws=warn,sp_io=warn,substrate_api_client=warn,jsonrpsee_ws_client=warn,jsonrpsee_ws_server=warn,enclave_runtime=warn,integritee_service=warn,ita_stf=warn
    networks:
      - integritee-test-network
    entrypoint: "dockerize -wait http://integritee-worker-1:4645/is_initialized -timeout 150s
      /usr/local/bin/integritee-service --clean-reset --ws-external -M integritee-worker-2 -T wss://integritee-worker-2
      -u ws://integritee-node -U ws://integritee-worker-2 -P 2012 -w 2102 -p 9912 -h 4646
      run --dev --skip-ra --request-state"
    restart: "no"
networks:
  integritee-test-network:
    driver: bridge
