services:
    lit-ts-api-package-build:
        image: litentry/litentry-cli:${RELEASE_IMAGE_VERSION:-latest}
        container_name: litentry-lit-ts-api-package-build
        volumes:
            - ../client-api:/client-api
            - ../cli:/usr/local/worker-cli
        build:
            context: ..
            dockerfile: build.Dockerfile
            target: deployed-client
        depends_on:
            litentry-node:
                condition: service_healthy
            litentry-worker-1:
                condition: service_healthy
        networks:
            - litentry-test-network
        entrypoint:
            "/usr/local/worker-cli/lit_ts_api_package_build.sh"
        restart: "no"
networks:
    litentry-test-network:
        driver: bridge