services:
  lit-get-account-nonce:
    image: integritee-cli:dev
    container_name: litentry-get-account-nonce
    volumes:
      - ../cli:/usr/local/worker-cli
    build:
      context: ..
      dockerfile: build.Dockerfile
      target: deployed-client
    depends_on:
      integritee-node:
        condition: service_healthy
      integritee-worker-1:
        condition: service_healthy
      integritee-worker-2:
        condition: service_healthy
    networks:
      - integritee-test-network
    entrypoint:
      "/usr/local/worker-cli/lit_get_account_nonce.sh -p 9912 -u ws://integritee-node
      -V wss://integritee-worker-1 -A 2011 -W wss://integritee-worker-2 -B 2012 -C /usr/local/bin/integritee-cli 2>&1"
    restart: "no"
networks:
  integritee-test-network:
    driver: bridge