services:
  lit-identity-direct-invocation-test:
    image: litentry-cli:dev
    container_name: litentry-identity-direct-invocation-test
    volumes:
      - ../ts-tests:/ts-tests
      - ../cli:/usr/local/worker-cli
    build:
      context: ..
      dockerfile: build.Dockerfile
      target: deployed-client
    depends_on:
      litentry-node:
        condition: service_healthy
      litentry-worker-1:
        condition: service_healthy
      litentry-worker-2:
        condition: service_healthy
    networks:
      - litentry-test-network
    entrypoint: "bash -c '/usr/local/worker-cli/lit_ts_test.sh test-identity-direct-invocation 2>&1' "
    restart: "no"
networks:
  litentry-test-network:
    driver: bridge
