services:
    lit-resume-worker:
        image: litentry/litentry-worker:latest
        container_name: litentry-worker
        volumes:
            - ../ts-tests:/ts-tests
            - ../client-api:/client-api
            - ../cli:/usr/local/worker-cli
        build:
            context: ..
            dockerfile: build.Dockerfile
            target: deployed-worker
        depends_on:
            litentry-node:
                condition: service_healthy
        networks:
            - litentry-test-network
        entrypoint: |
            /usr/local/worker-cli/lit_ts_api_package_build.sh -p 9912 -u ws://litentry-node -W http://litentry-node -V wss://litentry-worker-1 -A 2011 -C /usr/local/bin/litentry-cli 2>&1
            /usr/local/worker-cli/lit_ts_test.sh test-resuming-worker 2>&1
        restart: "no"
networks:
    litentry-test-network:
        driver: bridge
# docker compose -f docker-compose.yml -f resume-worker.yml up relaychain-alice relaychain-bob litentry-node --no-build --exit-code-from resume-worker -- resume-worker
