services:
    lit-evm-di-identity-test-test:
        image: integritee-cli:dev
        container_name: litentry-evm-di-identity-test-test
        volumes:
            - ../ts-tests:/ts-tests
            - ../cli:/usr/local/worker-cli
        build:
            context: ..
            dockerfile: build.Dockerfile
            target: deployed-client
        depends_on:
            integritee-node:
                condition: service_healthy
            integritee-worker-1:
                condition: service_healthy
            integritee-worker-2:
                condition: service_healthy
        networks:
            - integritee-test-network
        entrypoint: "bash -c '/usr/local/worker-cli/lit_ts_test.sh test-evm-di-identity-test 2>&1' "
        restart: "no"
networks:
    integritee-test-network:
        driver: bridge
