services:
    lit-data-providers-test:
        image: litentry/litentry-cli:latest
        container_name: litentry-data-providers-test
        environment:
            - CREDENTIAL_ID=${CREDENTIAL_ID}
            - ADDRESS=${ADDRESS}
            - EXPECTED_VALUE=${EXPECTED_VALUE}
        volumes:
            - ../ts-tests:/ts-tests
            - ../client-api:/client-api
            - ../cli:/usr/local/worker-cli
        build:
            context: ..
            dockerfile: build.Dockerfile
            target: deployed-client
        depends_on:
            litentry-node:
                condition: service_healthy
            litentry-worker-1:
                condition: service_healthy
        networks:
            - litentry-test-network
        entrypoint: "bash -c '/usr/local/worker-cli/lit_ts_dataprovider_test.sh -c $CREDENTIAL_ID -a $ADDRESS -e $EXPECTED_VALUE 2>&1' "
        restart: "no"
networks:
    litentry-test-network:
        driver: bridge
