services:
  lit-batch-test:
    image: integritee-cli:dev
    container_name: litentry-batch-test
    volumes:
      - ../ts-tests:/ts-tests
      - ../cli:/usr/local/worker-cli
    build:
      context: ..
      dockerfile: build.Dockerfile
      target: deployed-client
    depends_on:
      integritee-node:
        condition: service_healthy
      integritee-worker-1:
        condition: service_healthy
    networks:
      - integritee-test-network
    entrypoint: "bash -c '/usr/local/worker-cli/lit_ts_test.sh test-batch 2>&1' "
    restart: "no"
networks:
  integritee-test-network:
    driver: bridge
