services:
  lit-resume-worker:
    image: integritee-worker:dev
    container_name: litentry-worker
    volumes:
      - ../ts-tests:/ts-tests
      - ../cli:/usr/local/worker-cli
    build:
      context: ..
      dockerfile: build.Dockerfile
      target: deployed-worker
    depends_on: ['integritee-node']
    networks:
      - integritee-test-network
    entrypoint:
      "bash -c '/usr/local/worker-cli/lit_ts_test.sh test-resuming-worker 2>&1' "
    restart: "no"
networks:
  integritee-test-network:
    driver: bridge

# docker-compose -f docker-compose.yml -f resume-worker.yml up relaychain-alice relaychain-bob integritee-node --no-build --exit-code-from resume-worker -- resume-worker
