services:
    lit-tee-vc-contracts-test:
        image: litentry/identity-cli:latest
        container_name: litentry-tee-vc-contracts-test
        volumes:
            - ../ts-tests:/ts-tests
            - ../client-api:/client-api
            - ../cli:/usr/local/worker-cli
        build:
            context: ..
            dockerfile: build.Dockerfile
            target: deployed-client
        depends_on:
            litentry-node:
                condition: service_healthy
            litentry-worker-1:
                condition: service_healthy
        networks:
            - litentry-test-network
        entrypoint: "bash -c '/usr/local/worker-cli/lit_tee_vc_contracts_test.sh contracts_depoly_request.test.ts 2>&1' "
        restart: "no"
networks:
    litentry-test-network:
        driver: bridge
