services:
    lit-di-vc-test:
        image: litentry/litentry-cli:latest
        container_name: litentry-di-vc-test
        volumes:
            - ../ts-tests:/ts-tests
            - ../client-api:/client-api
            - ../cli:/usr/local/worker-cli
            - ../client-api:/client-api
        build:
            context: ..
            dockerfile: build.Dockerfile
            target: deployed-client
        depends_on:
            litentry-node:
                condition: service_healthy
            litentry-worker-1:
                condition: service_healthy
        networks:
            - litentry-test-network
        entrypoint:
            "/usr/local/worker-cli/lit_ts_test.sh -p 9912 -u ws://litentry-node
            -V wss://litentry-worker-1 -A 2011 -C /usr/local/bin/litentry-cli -T test-di-vc 2>&1"
        restart: "no"
networks:
    litentry-test-network:
        driver: bridge
