services:
  resume-worker:
    image: integritee-worker:dev
    container_name: integritee-worker
    volumes:
      - ../ts-tests:/ts-tests
      - ../scripts/install_node.sh:/install_node.sh
    build:
      context: ..
      dockerfile: build.Dockerfile
      target: deployed-worker
    depends_on: ['integritee-node']
    networks:
      - integritee-test-network
    entrypoint: "bash -c '/install_node.sh && cd /ts-tests && yarn install && yarn run test-resuming-worker:staging'"
    restart: "no"
networks:
  integritee-test-network:
    driver: bridge

# docker-compose -f docker-compose.yml -f resume-worker.yml up relaychain-alice relaychain-bob integritee-node --no-build --exit-code-from resume-worker -- resume-worker
