services:
  ts-tests:
    image: integritee-cli:dev
    container_name: integritee-vc-test
    volumes:
      - ../ts-tests:/ts-tests
    build:
      context: ..
      dockerfile: build.Dockerfile
      target: deployed-client
    depends_on:
      integritee-node:
        condition: service_healthy
      integritee-worker-1:
        condition: service_healthy
      integritee-worker-2:
        condition: service_healthy
    networks:
      - integritee-test-network
    entrypoint:
      "/usr/local/worker-cli/vc_test.sh 2>&1"
    restart: "no"
networks:
  integritee-test-network:
    driver: bridge